### ISSUE TITLE
[Settings] Match UI from Mockup

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#10]
See "Settings" section from: [https://da-vinci-rules-daver78.c9users.io/httpdoc/daver/dv.php](https://da-vinci-rules-daver78.c9users.io/httpdoc/daver/dv.php)

Suggest we divide each area in this way to make it easier for the User to identify the areas they can 'set'.

@paagla123 Please confirm this makes sense to you.  Otherwise, this page will get rather long.  If you agree, please assign to right team member.

**Comment by paweenwich** [comment]
How about make it tab-like instead of left menu.

**Comment by daver78** [comment]
@paweenwich I think with tab (left to right) we will run out of room, which is why I did it top-to-bottom.

@paagla123 thoughts?

**Comment by daver78** [comment]
@paagla123 and @paweenwich This is something you can assign to @AumpaiFung?

**Comment by paagla123** [comment]
@daver78 @paweenwich I believe we will need to have these top to bottom - that's kind of how all modern UI's seem to work - right?

**Comment by daver78** [comment]
@paagla123 I'm closing this one since I have the feature flag referenced in #139.
