### ISSUE TITLE
[eBook] Download.html page does not link to eBook content

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#105]
I have created the eBook campaign KD-1003-eBook-003.  The eBook has been uploaded to the following location: https://bkktest.s3.amazonaws.com/tmp/eBOOK-3a997cf3-4a5f-4ce1-8b35-7017f56ccc6e.pdf 

The download link from the download.html page should href to this location - it does not. See screenshot below.
![image](https://user-images.githubusercontent.com/29718335/31144720-65727d38-a836-11e7-963f-61e81199cc58.png)

**Comment by coa0329** [comment]
I cannot repeat it.

This is the link I get when I click that button :

http://dv16916.m.mdl.io/redirect?SessionGuid=cac936cb-bced-4fb2-9182-6174fb90f343&url=https://bkktest.s3.amazonaws.com/tmp/eBOOK-3a997cf3-4a5f-4ce1-8b35-7017f56ccc6e.pdf

And I can download that file.

**Comment by paagla123** [comment]
@coa0329 you are right. This works. Its a little confusing - @daver78 can we please discuss this user interface?
