### ISSUE TITLE
[eBook] Triggered emails are not being sent out when the Welcome page has been visited or the eBook downnload link has been clicked in the Download page

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#106]
I believe this is because the ##fromemail## variable is not being set in Studio. It is set in couchDB, but somehow not making it to Studio.
@coa0329 @jiewsone please get this fixed asap.

**Comment by coa0329** [comment]
Fixed on stage.

**Comment by paagla123** [comment]
Fixed on stage
