### ISSUE TITLE
[eBook] MAML gets published even before all steps of the accordion have a green check mark each

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#111]
The MAML is published at this time, although not all steps in the daVinci campaign have a green checkmark each. 

![image](https://user-images.githubusercontent.com/29718335/31195795-4832d784-a900-11e7-82ce-f619761a9d04.png)

**Comment by paweenwich** [comment]
@paagla123 @daver78 
I need a clear direction on this.  At first (promoteBlog), we have "publish/launch" button, which will enable and publish when all step is complete.   Later, we think it is a bad idea to have the launch button.  So, we experiment by using "publish when save".   If I remember correctly, Dave even suggest to publish when program first created (after name it) like his mock up..   

Do you still want us to check all steps before publish?

**Comment by paagla123** [comment]
@paweenwich @daver78 based on discussions I am going to close it. No need to fix. Thx
