### ISSUE TITLE
[Audience] Browse Contacts does not work correctly

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#113]
Account is daVinci - when I click on "See All My Contacts" it brings up a blank list - opens in a different tab.

When I click on a segment to view the contacts that belong to a segment that the list opens up the list, but in the same tab. It used to open in a different tab. Someone broke it!

**Comment by coa0329** [comment]
https://github.com/coa0329/BhaangWeb/commit/f1ae3bc6b3813faa19e302bcf8cfc347297490a1?diff=unified


target="_blank" was removed from the code.

**Comment by daver78** [comment]
@paagla123 Ah now someone is learning to use `git` :)

No, it wasn't broken, I removed it about 2 weeks ago.  I tagged you in the issue and you didn't find a prob with it.  We can easily change it back -- but why do you feel it needs to be new window?

**Comment by paagla123** [comment]
@daver78  Not a new window - new tab.
Because it is not part of the application - its just a spreadsheet - data. 
Should stay out of the application flow.

**Comment by coa0329** [comment]
@paagla123 
Do you want us to put target="_blank" back ?

**Comment by paagla123** [comment]
@coa0329 yes please. I already talked to @daver78 . He has given up!

**Comment by coa0329** [comment]
@paagla123 Fixed on stage.
