### ISSUE TITLE
[Email Footer] does not pull from latest content in settings section

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#114]
Once the campaign is saved (not launched), the email footer content does not change even if we change the settings. Of course if it is launched, it cannot change. @daver78 @paweenwich we need to discuss this - what is the right thing to do here?

**Comment by daver78** [comment]
@paagla123 I don't understand what you mean "_of course if it is launched, it cannot change._"

Why not?  This is the beauty of URL-based content.  It should update everywhere regardless of whether we've hit the launch button.

Maybe you mean if the email is already in the inbox of the person, we can't change it at that point?

If that's the concern, we could still change it, but that would require more work.  Not sure we need to do that now.

**Comment by paagla123** [comment]
@daver78 launched means email already sent. We don;t need to worry about that. Only when it is still not sent we should pull the latest.

**Comment by daver78** [comment]
@paagla123 Got it.  Are we not using URL-based content for this portion?

**Comment by paagla123** [comment]
@daver78 Yes we are - guess we're not updating it

**Comment by coa0329** [comment]
Solution :

1 When we save setting we will upload the value of defCompanyAddress, defCompanyPhone, defCompanyName, defCompanyLogo, defViewOnline and defUnsubscribe to S3. 
2 Create new 6 content variables in MAML : companyAddress, companyPhone, companyName, companyLogo, viewOnlineMessage and unsubscribeLinkS3.
3 Set content of each variables to the links in S3.
Example : The value of companyAddress is ##URL SRC="https://s3-us-west-1.amazonaws.com/bkktest/tmp/{{accountID}}-defCompanyAddress.html"##
4 Change the template to use content variables in #2

**Comment by paagla123** [comment]
@coa0329 I will test

**Comment by coa0329** [comment]
@paagla123 : Fixed on stage.
