### ISSUE TITLE
BACKLOG: [Blog] Need to provide different UTM's for the links from Hero Image and the Button

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#117]

**Comment by daver78** [comment]
@paagla123 Nice touch.  Will be good for marketer to be able to measure this.

We also need to add this to reporting in a simple and meaningful way.  I have some ideas.

**Comment by daver78** [comment]
@paagla123 What should we do about this?  If I move the UTM to the "optional" section on that page, I can add a way to differentiate between button & image click.

**Comment by paagla123** [comment]
@daver78 you mean the click through to the blog from the Hero Image vs the button? yes by all means.

**Comment by daver78** [comment]
@paagla123 OK I'll do this with `revamped_schedule` feature toggle.

**Comment by daver78** [comment]
@paagla123 I'm going to backlog this.  While some will need it, it is not absolutely necessary for launch.  If you feel otherwise you can resurrect it.
