### ISSUE TITLE
[Blog]  Need to be able to change background color for the CTA button

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#118]

**Comment by daver78** [comment]
@paagla123 Agreed.  

Opinion: This should be set globally (set once and forget), or configurable p/email?

What say you?

**Comment by paagla123** [comment]
@daver78 per email will be better.

**Comment by daver78** [comment]
@paagla123 How about you set it globally as your default.  Think of it is as your global "style guide".  Set once, forget about it.

However, at the individual email level, you can override it if you need to.

Is that OK?

That said, you should ask Mac.  Does she, as the user, want to change the color from email to email?

I wish I could tag her in here!

**Comment by paagla123** [comment]
OOK

**Comment by paagla123** [comment]
@Mcfarsheed can you pl look at Dave's comments above and respond?

**Comment by Mcfarsheed** [comment]
HI All -- Kush thanks for tagging me. I think you should set a default and then be able to override in each email. If we make someone configure it in each email, I think it's too much manual work and thought. But we should definitely give them the option to override. For example, I usually want my default to be orange but if my email header image is blue, I may want to be able to change the button to blue to match.

**Comment by paagla123** [comment]
@coa0329 @jiewsone please put this as an option in Settings section under Company Logo.
The Field label should say - color of CTA button
Should show the current color (default green) in a box next to field label. Click the box to open the pallet, select new color and save.

**Comment by Mcfarsheed** [comment]
Thanks @paagla123 -- in this case, this would make the color they choose be universal for all emails right? Would they have the option to change it in the specific email?

**Comment by paagla123** [comment]
@Mcfarsheed no email specific changes. If that becomes too hard, we will add that in a future release

**Comment by daver78** [comment]
@paagla123 and @jiewsone I imagine we should us something like this: [https://farbelous.github.io/bootstrap-colorpicker/](https://farbelous.github.io/bootstrap-colorpicker/)

There is likely an `angularjs` directive for something similar; I did not check.

**Comment by paweenwich** [comment]
Done

**Comment by Mcfarsheed** [comment]
Nice!

Sincerely,

Mackenzi
MindFireInc.
949-842-4388
www.mindfireinc.com

**Comment by paagla123** [comment]
Perfect!
