### ISSUE TITLE
Any time you edit a blueprint, minimize left nav

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#12]
This will avoid the form overrun. Make sure it stays locked in minimized state. Also use tool tip while hover in minimized state. For minimized experience, visit https://da-vinci-rules-daver78.c9users.io/httpdoc/daver/dv.php.

**Comment by paagla123** [comment]
Related to #14

**Comment by daver78** [comment]
@paagla123 Looks like we did this only in the accordion step that has the issue (not upon entering the Blueprint).  Are you OK with this user experience?  What do you think?

(I'm not opposed to it just asking for opinion)

**Comment by daver78** [comment]
@paagla123 I'm closing this until you decide what you want to do here (if the current implementation is not enough).
