### ISSUE TITLE
Program Name Too Long Error

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#121]
I got this error at the end when launching the program - should get it right at the beginning when we enter the name. Perhaps have a character counter like in LWC SMS

**Comment by daver78** [comment]
@paagla123 Great idea.  If I recall Studio limit is 50 chars -- but do we need some chars for our own internal DV naming structure?

For now, please assign to someone to limit the # of chars that can be put into the field for both PABP and PAEB.  

If someone has time, they should find the angularjs way of showing chars remaining (should be easy).

**Comment by jiewsone** [comment]
Fixed on stage.

**Comment by paagla123** [comment]
Works as well - not allowed to enter more than 50 characters
@daver78 we're probably going to need some love here in terms of error messages. Pl take a look and let me know, we can create a new issue.
