### ISSUE TITLE
[Blog] When we copy from previous email - we need to copy the subject as well

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#122]

**Comment by daver78** [comment]
@paagla123 Agreed.  Removing me from assignees so my discrete tasks are clear.  Add me back if you need me to do something.

**Comment by coa0329** [comment]
@jiewsone will fix this.

**Comment by paagla123** [comment]
@coa0329 I am reopening this issue. Problem is, when you copy an email in the Blog, the subject is copied in DaVinci, but when published, Studio does not have the subject unless you copy and paste the subject explicitly.  See Email3 of DaVinci "Campaign Enrollment Services PODCast - Seed v3".
Screenshot of Email3 from DV - has correct subject:
![image](https://user-images.githubusercontent.com/29718335/31248387-6a73477a-a9c8-11e7-8b9a-66b704e3fe80.png)
View of email3subject in Studio
![image](https://user-images.githubusercontent.com/29718335/31248438-92dffb90-a9c8-11e7-95b1-08b400fe5d18.png)
Content in S3 - still shows default content
![image](https://user-images.githubusercontent.com/29718335/31248455-a4a45f10-a9c8-11e7-8f4c-080125231604.png)

**Comment by paagla123** [comment]
Fixed.
