### ISSUE TITLE
[Blog] UTM string got removed when using  shortened URL to Blog

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#123]
Shortened URL pointing to Blog when expanded eliminated the UTM string. We need to discuss our strategy of using shortened URLs

**Comment by daver78** [comment]
@paagla123 Is this specific to DV/Studio -- or does it happen in general?

**Comment by paagla123** [comment]
@daver78 Saw this with DV so far. I imagine if it happened in general Mac would have complained by now.

**Comment by daver78** [comment]
@paagla123 Hmmm.  Would be interesting to verify that.  How come I can't tag Mac in here?  Did we not invite her?

**Comment by coa0329** [comment]
![157](https://user-images.githubusercontent.com/7914690/31206397-c40f33ce-a9a1-11e7-9a8c-1fa6beaf3092.JPG)


They are invited. Waiting for them to accept.

**Comment by paagla123** [comment]
@coa0329 send me the invite links please.

**Comment by coa0329** [comment]
This is the link when I click "Copy invite link"

https://github.com/coa0329/BhaangWeb/invitations

**Comment by daver78** [comment]
@paagla123  Is this specific to DV/Studio -- or does it happen in general?

**Comment by paagla123** [comment]
@daver78 @javpowell 
I tested in Studio - same thing happened. So I am closing this  from DV - this is a Studio bug.
When we use shortened URL and put UTM code after it, Studio removes the UTM codes when the URL gets expanded.
To replicate, login to Studio as kdutta@mindfireinc.com, open program Autodemo_02162016, send teh email called DriveEmail to yourself and then click on the link in the email that says "View our blog". 
The code there is:
`<a href="http://wp.me/p3eiLo-Ku?utm_source=Email&utm_medium=Email&utm_campaign=Podcast&utm_term=PodcastEpisode36&utm_content=FirstLink">Visit our BLOG</a><br><br>`

It expands to:
![image](https://user-images.githubusercontent.com/29718335/32272927-79ab3fea-bebd-11e7-85de-18ec7bbf9789.png)

This is pretty serious - users are missing tracking info, as this is a fairly common thing to do. I know Mac does it - that's how we blundered into it.

**Comment by javpowell** [comment]
@paagla123 are you sure this works in the real world the way you are doing it? You may need to URL encode the query string to do it properly so that the browser does not drop it. If you feel its a Studio bug, please escalate to support.

**Comment by daver78** [comment]
Woah hold up kids.  I think this is user error ... sorry :)

**In general, my recollection/belief is that if you wish to add tracking params to your link, for example Google Analytics UTM codes, simply append them to the end of your long URL _before_ shortening.** 

I do not believe this is a Studio bug.

I do not believe this is a serious issue.

Sorry @paagla123, no need to get excited :)  @javpowell No need to do anything.  Let's close this one, @paagla123, unless you can prove me wrong.
