### ISSUE TITLE
[PABP] Give User a way to test their sequence, and create multiple waves <feature flag = revamped_schedule>

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#127]
@daver78 after the production run with Mac, I believe we need to have a test run and a production run after the campaign is published.

**Comment by daver78** [comment]
@paagla123 YES YES YES YES!!!  Beautiful.  Was counting the minutes until you added this.  Praise the Lord!  We'll talk @ our meeting.

**Comment by daver78** [comment]
Dave will do the UI with a feature flag on this one.

**Comment by daver78** [comment]
Notes between the esteemed @paagla123 and Dave as to how this might work:

- User configures Steps 1 and 2 as usual.
- When she arrives at Step 3, she sees 4 tabs or waves or something.  The first tab is called “Test Wave”.  This one is on.  There are 3 others, but she can’t click on them.
- She picks a test audience, a start time (within the day), and an interval.  Pushes a button that says DO IT.
- She can do it again and again.  As many times as She wants.
- Once she has clicked the TEST BUTTON once, then she can click Wave 1 and sees the scheduling the way it is now.

**Comment by daver78** [comment]
![image](https://user-images.githubusercontent.com/7561473/31302586-a2d36e66-aab7-11e7-826e-564ad2fd0462.png)

**[A]** Is the schedule.  You set it once.
**[B]** Appears maybe immediately or after you configure your schedule
**[C]** Is where you add your “waves” … like in your case, “Prospects” and “Clients” and “MarTech People”
**[D]** Is where you add another one

**Comment by paagla123** [comment]
@daver78 I assume this needs to be merged into the Staging right?

**Comment by paagla123** [comment]
@daver78 comments from this morning:
New layout:
- missing button to upload picture
- Some love needed in the display of name and emails in the two tabs on right
  Not enough room - from and test emails
- The tabs should automatically roll back if I click outside of the tabs
  If not possible, pl provide some sort of a x to close - not intuitive to click on name to close
- We still have to solve the question on who the triggers go to.
   May be that option should be added when you select the triggers, or in the settings

**Comment by daver78** [comment]
@paagla123 during last night's chat @paweenwich asked if the changes should be made to this revamped version.  You said "OK sure" -- but to clarify, I want to make sure the answer is "YES" without any doubt.  

Using the feature flag will help us determine if this is the right way to do things in the future.

Any subsequent changes I make to this area will continue using the feature flag, and the team should do the same.

**Comment by paagla123** [comment]
@daver78 @paweenwich please note: OK SURE == YES. 🥇

**Comment by paagla123** [comment]
@daver78 we do not need launch!

**Comment by daver78** [comment]
@paagla123 OK sure ;-)

**Comment by daver78** [comment]
@paagla123 Do we still need this open?

**Comment by paagla123** [comment]
@daver78 I am going to test this quite a bit before closing.

**Comment by paagla123** [comment]
@daver78 closing this one. Some issues left open still - listed under #191 .
