### ISSUE TITLE
[eBook] Copy campaign.

### ISSUE THREAD

**Issue by coa0329** [coa0329/BhaangWeb#135]
@paweenwich 
We need to publish the new campaign after user set the name.

**Comment by paweenwich** [comment]
Done.  however, because publish, will take a while, So, after copy completed message, (we secretly publishing at this stage), you can not navigate to other pages.

**Comment by paagla123** [comment]
@coa0329 @paweenwich What is this one about? Thx

**Comment by coa0329** [comment]
@paagla123 

When user copy eBook campaign, we let them enter the new campaign name, click 'ok', then we close the popup.

If we don't publish it, user cannot visit the microsite. They will get error "Sorry, I can't find a Microsite to display.". 

So we must find the place to publish it. 

My idea is to do it after they enter the new campaign name.

**Comment by paagla123** [comment]
OK - its a good idea. @coa0329 please go for it. Thanks

**Comment by coa0329** [comment]
@paagla123 

Fixed on stage.
