### ISSUE TITLE
[Settings] Logo is not being saved

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#136]
When I upload a new logo and save it, it shows the new logo. However, when I go to another tab, and come back to settings, it still shows the old logo.

**Comment by jiewsone** [comment]
@paagla123 
I guess it's cache problem.
I cannot repeat it everytime. 
I have add Cache Control when we upload logo file for fix it.
However I will re-check it again. if it still happen.
If it's happen, please try to click ctrl+f5 to refresh page.

I have upload to production.
Please go to setting then click save after you login for the first time to make sure all dafault value was uploaded to S3.

**Comment by paagla123** [comment]
@jiewsone OK - this is working fine.  However, I found one other issue, the logo uploaded gets placed in both staging and production. Can we separate stage from production please? Thx
