### ISSUE TITLE
Create a Campaign allows user to go to building of the campaign without typing a name

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#137]
As a result I have two campaigns with blank names now:
![image](https://user-images.githubusercontent.com/29718335/31569908-c8255c34-b033-11e7-8be5-e6308b511642.png)

You can rename these campaigns - so it may be ok to leave them this way. I feel that we should have a pop-up at the time of the first SAVE to force people to type a name.

If I try to Publish - I get a Program Name Missing Error:

![image](https://user-images.githubusercontent.com/29718335/31569954-34a8fed8-b034-11e7-9b12-da7ff742bb04.png)

**Comment by jiewsone** [comment]
@paagla123 @daver78 
Fixed on stage.
I have a question.
On create new campaign, I have show warning message like this.
![validate_campaignname4](https://user-images.githubusercontent.com/30495168/31771851-d04b9f58-b507-11e7-98cf-3ae5fe8ae233.JPG)
I think it better than show pop up on modal form again.

But on edit campaign name, I have 2 choice.
1. Use function validate of xeditable. (I use this now)
![validate_campaignname5](https://user-images.githubusercontent.com/30495168/31772184-062afc1c-b509-11e7-882c-744a7fe222e2.JPG)
I think it's user friendly, but I cannot assign another code on it.
I can change wording and a little text css (text color and text shadow)

2. Check validate after click xeditable submit button.(the orange button)
It's free, I can show pop up like this.
![validate_campaignname2](https://user-images.githubusercontent.com/30495168/31772742-d49a4c28-b50a-11e7-9933-efdcf16291b1.JPG)
But we can see "Empty" like the red circle on the image between the pop up show up.
when we close pop up I can set it to old campaign name like this.
![validate_campaignname3](https://user-images.githubusercontent.com/30495168/31772955-62e168e0-b50b-11e7-84be-62326d91373b.JPG)
But user have to click it again to change campaign name.

What do you think about it?

**Comment by daver78** [comment]
@jiewsone Did you check the `x-editable` params carefully to see how they handle validation? I imagine there must be something there that helps us with this use case.  Or no?

**Comment by jiewsone** [comment]
I have research it, but I don't found anything and it take more time then I switch to do the other issue.
What is the goal that you need?

**Comment by paagla123** [comment]
Closing this one!
