### ISSUE TITLE
[Settings] Revise UI to group similar settings together in a tab format <feature flag = tabbed_settings>

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#139]
Finished.  Make sure you have access to feature toggle `tabbed_settings`.

![image](https://user-images.githubusercontent.com/7561473/31978075-80f8e014-b8f4-11e7-9816-8edb244c78ec.png)

![image](https://user-images.githubusercontent.com/7561473/31978080-8ed59d62-b8f4-11e7-90bd-efc53c998689.png)

![image](https://user-images.githubusercontent.com/7561473/31978097-9cad155a-b8f4-11e7-9d7c-d702da8bfaee.png)

![image](https://user-images.githubusercontent.com/7561473/31978105-a87349ae-b8f4-11e7-8a8a-ea49accfb61b.png)

![image](https://user-images.githubusercontent.com/7561473/31978117-b450ee8e-b8f4-11e7-8a1c-7f0b9b1494f7.png)

![image](https://user-images.githubusercontent.com/7561473/31978126-bf2436b8-b8f4-11e7-9d41-c9d2316aa23c.png)

![image](https://user-images.githubusercontent.com/7561473/31978151-d0ad770a-b8f4-11e7-9831-218669d258fd.png)

**Comment by daver78** [comment]
@paagla123 and @coa0329 this is ready for implementation.

**Comment by paagla123** [comment]
@daver78 can we discuss this one please?

**Comment by daver78** [comment]
@paagla123 Yes, go ahead.  Listening.

**Comment by paagla123** [comment]
@daver78  we need to discuss f2f as I don;t understand what you want

**Comment by daver78** [comment]
@paagla123 OK.  What part is unclear?  Maybe you don't have access to the revised UI for this portion.  Is that the issue?

**Comment by paagla123** [comment]
@jiewsone what is the status here? Thanks

**Comment by paagla123** [comment]
@daver78 please give permission to kdutta@mindfireinc.com for new UI
@coa0329 in the global settings tab please add color changing ability for the buttons
@daver78 please discuss your vision on email protection (how to implement), grading and scoring, billing.

**Comment by paagla123** [comment]
@coa0329 can you please add the color changing ability for buttons in this tab?

**Comment by coa0329** [comment]
@paagla123 

1 I put the color picker in global settings tab.
2 I put save and cancel button in global settings, email settings and Integrations tab.

**Comment by paagla123** [comment]
@coa0329 will test over weekend.
