### ISSUE TITLE
[Global Settings] Setting for "no more than x emails p/person p/[timeframe]" <feature flag = tabbed_settings>

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#143]

**Comment by daver78** [comment]
@paagla123 Do you agree with this?  I think it will serve to protect Users, which we have failed to do in the Studio UI.  There are other areas in which protection is required, but this is a good start.

**Comment by paagla123** [comment]
@daver78 Yes something like this - probably low priority. Per day is too much - we should discuss

**Comment by daver78** [comment]
@paagla123 I'll put a placeholder in Settings #139 for now.

**Comment by daver78** [comment]
@paagla123 I'm closing this for now.
