### ISSUE TITLE
[PABP] Create updated MAML to support feature flag == revamped_schedule

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#145]
@paagla123 I'm creating this task for you to create the MAML that the team will need to handle the revised UI.

**Comment by paagla123** [comment]
@coa0329 I have added a ver12 of teh MAML to add three additional TAs for each email

**Comment by coa0329** [comment]
![010](https://user-images.githubusercontent.com/7914690/31699262-351c1f74-b3ec-11e7-92f5-f82f8ea5cad9.JPG)

I modify ver12 by adding more schedules to all emails.

**Comment by coa0329** [comment]
@paagla123 

Switch to use ver12 on stage.

**Comment by paagla123** [comment]
Closing
