### ISSUE TITLE
[Setting] Hover over the side bar

### ISSUE THREAD

**Issue by kkhalessi** [coa0329/BhaangWeb#147]
When hovering over the orange area,   it’s only showing the text related to the image when you are right at the image (yellow square area), it’s good to cover the whole orange area. Please see the screenshot:
https://www.screencast.com/t/2Gl5rDn0degH

**Comment by daver78** [comment]
@paagla123 What's your question?  Let me know.

**Comment by daver78** [comment]
@paagla123 and @kkhalessi can you review this one?  I don't follow.

**Comment by paagla123** [comment]
@daver78 I can explain what she means when I see you next time

**Comment by daver78** [comment]
@paagla123 OK.  Is it something that needs to happen by T-day?  If not, let's backlog it?

**Comment by paagla123** [comment]
Not urgent

**Comment by daver78** [comment]
Putting in backlog.
