### ISSUE TITLE
When "Create Campaign" modal pops up, focus should be in text input

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#148]
![image](https://user-images.githubusercontent.com/7561473/31699482-28679d86-b378-11e7-8f5b-a0168277744f.png)

**Comment by daver78** [comment]
@coa0329 Oh, thank you!  Did you do the same for the other Blueprint's modal?

@paagla123 Will you check this?

**Comment by coa0329** [comment]
@daver78 Yes, both blog and ebook.

**Comment by paagla123** [comment]
Its fixed thx
