### ISSUE TITLE
Optimize MAML render 

### ISSUE THREAD

**Issue by paweenwich** [coa0329/BhaangWeb#15]
![capture](https://user-images.githubusercontent.com/17819797/30625398-3107c812-9ded-11e7-9f22-c17a01f41001.PNG)

**Comment by paweenwich** [comment]
Suspect most of the time is s3 copying.

**Comment by paweenwich** [comment]
![capture](https://user-images.githubusercontent.com/17819797/30626446-257d092e-9df4-11e7-9b93-fa4084c1a73d.PNG)

S3 upload confirm

**Comment by paweenwich** [comment]
![capture](https://user-images.githubusercontent.com/17819797/30626994-cae283c8-9df7-11e7-9739-3d777c4c2b76.PNG)

BTW all above result was obtain from VirtualBox in my machine (Thailand)

**Comment by paweenwich** [comment]
![capture](https://user-images.githubusercontent.com/17819797/30627694-178bd68a-9dfc-11e7-9548-79e9ff02d564.PNG)

This is time in staging.   So, S3's time seem ok.

**Comment by daver78** [comment]
@paweenwich and @paagla123 :)

**Comment by paweenwich** [comment]
I will close this.

**Comment by daver78** [comment]
@paweenwich Thank you.
