### ISSUE TITLE
BACKLOG: [Asset Library] Use meta info to protect User from inappropriate Assets

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#150]
If we tag assets with the corresponding media they can be used in, we can then filter the Asset Library views so that if I'm working on an email, I only see Assets that I can use in an email.

This could make the UX better, safer.

**Comment by daver78** [comment]
@paagla123 What do you think?  Should we backlog this for now but consider it later?  I saw that Concentrix is doing this in their Asset Library.

**Comment by paagla123** [comment]
@daver78 Backlog for now please.
