### ISSUE TITLE
Adding  new accounts/beta clients to da Vinci

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#151]
@coa0329 please ensure that someone can add new accounts to DV in your absence. Also - if you can document the process (how to add a new Studio acct to DV) here, it will be great. Thx

**Comment by coa0329** [comment]
1 
Stage : Go to http://162.243.155.57:5985/_utils/database.html?master/studioAPI
Prod : Go to http://web2xmm.com:5984/_utils/database.html?master/studioAPI

![013](https://user-images.githubusercontent.com/7914690/31758688-a0cfc9e0-b4d8-11e7-868d-4a1710cb59cd.JPG)


2 Click Source.
3 Double click Source to edit.
4 Add new record at the bottom of apiCredential
       ,{
           "accountname": "",
           "PartnerGuid": "",
           "PartnerPwd": ""
       }
5 Click the green check icon.
6 Click Save.

Note : Please be careful to about comma.

**Comment by paagla123** [comment]
Done - thanks
