### ISSUE TITLE
[Reporting] Create a RedShift Environment for DV Reporting

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#156]

**Comment by amalekshahi** [comment]
I need schema for the table(s) that you want created on Redshift.

**Comment by paagla123** [comment]
@daver78 should we provide a schema based on the data returned by GA API? Thoughts?

**Comment by amalekshahi** [comment]
Yes

**Comment by paagla123** [comment]
That question was for @daver78 to answer 👍

**Comment by daver78** [comment]
@amalekshahi Good to see you here where all the action is :)

@paagla123 As discussed, let's wait to see where you end up with the GA/conversion issue.  I'm getting the sense I may need to spend some time thinking about it again if the fingerprint method doesn't pan out.

**Comment by paagla123** [comment]
@AumpaiFung can you please add your schema requirement here for assets library?

**Comment by AumpaiFung** [comment]
@paagla123 
We want 2 DB (for prod and stage).

TableName : S3FileDescription
Field: 
	ID			ID
	lasteditdate	Datetime
	accountID	varchar(10)
	programID	varchar(10)
	filename		varchar(100)
	awspath		varchar(100)
	pageuse		varchar(1)(Y/N)
	description	varchar(500)
	dimension	varchar(50)
	duration		varchar(50)
	filetype		varchar(50)

**Comment by paagla123** [comment]
@amalekshahi here is your answer re RedShift schema. Pl let us know when this can be done. Thanks.

**Comment by amalekshahi** [comment]
@AumpaiFung - Questions:
- Is the ID an integer field? Do you want that auto-increment or you will pass the ID for inserts?
- Are AccountID and ProgramID the same ones as in Studio data? If so, why don't you have them as integers? Integers take less space and are faster it queries
- PageUse: Are you Ok with data type Boolean for this field? Boolean data type is more efficient than string
- Duration: I am not sure what this field is this but can this also be an integer?
- Have you worked with Redshift before? How will you insert/ update data and select from it?

I will create this table in staging first and provide you with credentials to work with that. The production table will be created when you are ready.

**Comment by AumpaiFung** [comment]
@amalekshahi 
1. ID is auto-increment
2. AccountID is the same with Studio, but programID is not.
3. PageUse could be boolean. 
4. Duration is video / audio duration time, I think it should not be integer.
5. I never work with Redshift before, and now still have no idea about how to insert, update and select data. 
------------------------------------------------
New schema : 
TableName : S3FileDescription
Field:
ID                  auto-increment
lasteditdate   Datetime
accountID     int
studioprogramID    int
programID    varchar(50)
filename        varchar(100)
awspath         varchar(100)
pageuse        boolean
description    varchar(500)
dimension     varchar(50)
duration        float
filetype          varchar(50)

Thank you for your suggestion.

**Comment by amalekshahi** [comment]
I recommend changing everything that is essentially integer to integer data type. You got to think about the storage and performance for things like queries and sorting. 
- Why do you want ProgramID as varchar when it is integer?
- Also you can save duration as minutes or seconds (integer) instead of float. You can always present 380 minutes as 06 h and 20 mins to users.
- Where is the source data (for insert to Redshift) coming from? Can you tell me about your use case?

**Comment by paagla123** [comment]
@amalekshahi Source data is the asset manager in daVinci. You can log into incistage.mindfireis.com/admin/login.html using my email and MindFire2012 as pwd, go to Davinci account and go to asset manager, you will get the idea.

**Comment by paagla123** [comment]
@amalekshahi can you please provide some documentation and sample code of how to connect to the RedShift DB and insert, select, update etc?

**Comment by AumpaiFung** [comment]
@amalekshahi 
1. ProgramID of davinci is something like this >>5ba63afb49811f82e6c17f260bdb32a1. 
So I will change field name from programID to campaignID. 
And studioProgramID change to programID also. 

2. About duration time I think it's just file detail to display, it's not nessessay to calculate everytime to display or sorting.
Please define it to varchar(8)

TableName : S3FileDescription
Field:
ID auto-increment
lasteditdate Datetime
accountID int
programID int
campaignID varchar(50)
filename varchar(100)
awspath varchar(100)
pageuse boolean
description varchar(500)
dimension varchar(10)
duration varchar(8)
filetype varchar(50)

**Comment by daver78** [comment]
@paagla123 Don't forget to discuss this with team; I'm not sure why we need Redshift here.  Couch should be sufficient and faster, easier for @AumpaiFung.

**Comment by paweenwich** [comment]
@daver78 Without relational database, this will be difficult.  For example, suppose we need to add/insert/modify single record.  In CouchDB we need to get all records, writing code to find the record (incase of modify or delete), perform add/insert/delete  then  save all records back to database.   Moreover, if there are more than one session doing this.  Only first save will success and other will fail.  Even, other session just add or modify completely different record. 

This trouble will not occur for RDB.  

Do we need to use Redshift?  Can we use MySQL?  Data is not that Petrabyte anyway.

**Comment by daver78** [comment]
@paweenwich I agree.  I'd prefer not to use Redshift so there is no "block" in completing the task.  If we're going to use MySQL, I'd eventually like it to be as-a-service from AWS, but we can run it on the machine for now unless @paagla123 throw a fit! :)

**Comment by paagla123** [comment]
@daver78 we spoke - me, @paweenwich and @coa0329 . We will use the MySQL on Google Cloud. I need the billing account setup. We have done the initial estimate - right now it will cost around $17 per month.
I am closing this issue as we don;t need this any more.  I'll open a new one re Google Cloud SQL
