### ISSUE TITLE
[Blog] Added new Email Templates

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#158]
Added two new templates and updated the file name of the one with centered CTA
![image](https://user-images.githubusercontent.com/29718335/31845392-03510818-b5b5-11e7-82fa-5f3c464172e1.png)

**Comment by paagla123** [comment]
The new templates do not populate default content yet. May be the htmls need to be pished in stage. @coa0329 can you please check? Thanks

**Comment by coa0329** [comment]
@paagla123 

Where do you put those html ?

I cannot find them in BhaangWeb/html/admin/templates/emails/

![024](https://user-images.githubusercontent.com/7914690/31923380-60e0eccc-b8a4-11e7-8020-1dd64040ad41.JPG)

**Comment by coa0329** [comment]
I pull them to stage.

**Comment by paagla123** [comment]
Done
