### ISSUE TITLE
Obtain SSL for secure sign-up and DV

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#159]
If we are to gather credit card details during sign-up, we need SSL.

The DV UI should also employe SSL.

**Comment by daver78** [comment]
@paagla123 Who should this be assigned to?

**Comment by paagla123** [comment]
@coa0329

**Comment by coa0329** [comment]
@paagla123 
Which domain ?

**Comment by paagla123** [comment]
davinci.mindfireinc.com and dv.mindfireinc.com

**Comment by coa0329** [comment]
@paagla123 

Please purchase the certificate and send the information to Chay to install them.

**Comment by coa0329** [comment]
@paagla123 

This is the link we use now.
http://##purl##.dv{{accountID}}.m.mdl.io/{{campaignID}}/Email1.html

I am not sure this will work.
http://##purl##.{{accountID}}.dv.m.mdl.io/{{campaignID}}/Email1.html

**Comment by paagla123** [comment]
@coa0329 
For https Studio requires the PURL to be in virtual folder, e.g.,
https://{{accountID}}.dv.m.mdl.io/{{campaignID}}/##purl##/Email1.html

**Comment by paagla123** [comment]
@javpowell I have question for you here. 
We plan to add domain which will be formatted like:
https://{{accountID}}.dv.m.mdl.io/{{campaignID}}/##purl##/pagename.html

Question is - if we add SSL to dv.m.mdl.io, will it be able to handle all of the subdomains without having to buy a SSL for each one? Wht are our options here?

**Comment by daver78** [comment]
Two things we're talking about here:

1- The sign-up process will be at `dv.mindfireinc.com`, so we need this to have SSL. @paagla123 will work on this.

2- The other issue is how to put SSL on microsites.  @paagla123 just needs to test this.

**Comment by javpowell** [comment]
@daver78 @paagla123 

https://{{accountID}}.dv.m.mdl.io/{{campaignID}}/##purl##/pagename.html

will only work with a WildCard SSL, not our existing certificate. They cost around 700bux a year through entrust I believe.

**Comment by daver78** [comment]
@paagla123 Can you handle issue #2?  If we can't use mdl.io for some reason, let's get another generic domain and do it there.

It also looks like you own the next step on issue #1 too.  Please confirm.

**Comment by paagla123** [comment]
@daver78 let's discuss tonight. I am not sure I follow 100%

**Comment by daver78** [comment]
@javpowell From Kushal: If I buy a domain, like “mydv.com”, then can I use accountID.mydv.com, get SSL on *.myDV.com, then will that work for all such microsites?  Have you tested this, or are you saying it should work?

**Comment by javpowell** [comment]
I have not tested this, but this is how a WildCard certificate is supposed to work. So it "should" work.

**Comment by javpowell** [comment]
https://www.entrustdatacard.com/products/ssl-certificates/wildcard-ssl

**Comment by daver78** [comment]
@paagla123 Just did the infamous eye roll, "_Ohh Godddd ... fuuucccckkk ...._" :)

@javpowell He asks if you can have Kathy or Manasa purchase a wildcard SSL and set it up.  @paagla123 is sending you a domain later today.

**Comment by javpowell** [comment]
@daver78 @paagla123 how many years? 

1 $699 each |2  $608.13 /year |3 $573.18 /year

**Comment by javpowell** [comment]
Hold the brakes, just spoke to Kush and we need to figure out how to handle this certificate on the Microsite server now since we already have a cert there. Let me ask RF.

**Comment by paagla123** [comment]
@javpowell need another help here. I put my-dv.com in the cart, but cannot pay for it from here - credit card info comes up as blank. Can you please get together with Baker and complete the purchase? Then please have Iram or Pronit to get it to point to Studio - as well as stage.my-dv.com. 
This means we will need the SSL for my-dv.com and stage.my-dv.com. Thx

**Comment by javpowell** [comment]
@paagla123 @daver78 Domain purchased and DNS pointed to Studio. SSL has not been figured out yet. Stay tuned.

**Comment by paagla123** [comment]
@javpowell excellent thank you.

**Comment by javpowell** [comment]
@paagla123 @daver78 I have some follow up on the SSL side of things still. RF and I discussed how to make this happen Friday and I have a call with Entrust today. Stay tuned on next step here.

**Comment by paagla123** [comment]
@javpowell thanks. Pl open a new issue when you have some actionable item here/ Thx
