### ISSUE TITLE
[Settings] Please add option to change color of button text as well

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#160]
Otherwise if the button is made white background, the text is not readable.

**Comment by paweenwich** [comment]
@paagla123 I think the text properties including style/font/color can be changed by using summer note interface, by just selecting the text.

**Comment by daver78** [comment]
@paagla123 Are you finding the summernote "air" method difficult to use?

**Comment by paagla123** [comment]
@daver78 I am ok - I just did not expect this to be the solution - not sure why.
