### ISSUE TITLE
Use feature toggle to hide "Git" and "DB" links in UI

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#162]
@paagla123 Did you forget to add this?  We should do this soon since I think you have 2-3 "real" people in here now.

**Comment by paagla123** [comment]
@daver78 @paweenwich @coa0329 I suggest we do it only for Production and not for Stage - anyone agree?

**Comment by daver78** [comment]
@paagla123 Shouldn't matter.  If you use the feature toggle, only the specified users will see it in the UI.

**Comment by coa0329** [comment]
@daver78 @paagla123 
They will not show on prod.
They will show on stage.

**Comment by paagla123** [comment]
Tested - not showing in production as promised by @coa0329
