### ISSUE TITLE
[PABP] User can see ##vars## in Email

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#168]
When viewing the emails, I can see the `##defViewOnline## `at the top of the email, and `##vars##` in the footer.  The user should not see the vars: they should see the replaced values.

**Comment by paagla123** [comment]
![image](https://user-images.githubusercontent.com/29718335/32011227-fc20ffbe-b968-11e7-9e38-51e42d717222.png)

**Comment by coa0329** [comment]
@daver78 @paagla123 @paweenwich 

![026](https://user-images.githubusercontent.com/7914690/32088094-12ca975e-bb0b-11e7-9dab-de186e6d2659.JPG)


They are the variables in studio.

We need studio to render them.

**Comment by daver78** [comment]
@paagla123 and @coa0329 It didn't used to be this way.  Did we recently change something about our approach?

If we didn't use the Rule Group Variables in the MAML, would this be solved?

**Comment by paagla123** [comment]
@coa0329 can you please respond to this? Thx

**Comment by coa0329** [comment]
@daver78 @paagla123 

Please see https://github.com/coa0329/BhaangWeb/issues/114

**Comment by paweenwich** [comment]
@paagla123 Done.   However, DV can render only ##variable## that DV manage.  It can not render contacts variable (Ex. ##firstname##).

**Comment by paagla123** [comment]
This has tested OK
