### ISSUE TITLE
[Welcome] Hide table of Campaigns if User's first time and no campaigns available

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#17]
We need to come up with a way to introduce Users to different parts of the UI, especially if it is their first time in that portion of the UI.

For example, the Welcome Page for a first-time User shows an empty table.

Let's use an `ng-if` or something to hide the table if there are no Campaigns.

Later, we can have @paagla123 or someone else write content to help the User get started (including video or similar to WalkMe thingsy).

**Comment by daver78** [comment]
OK, good enough for now.  First time users see (needs love and clean up, we can do later):
![image](https://user-images.githubusercontent.com/7561473/30659731-9080b2a8-9df3-11e7-99cb-c79e25e68011.png)



Whereas users with existing campaigns see:

![image](https://user-images.githubusercontent.com/7561473/30659671-63c67c0c-9df3-11e7-9026-8715438ba252.png)

@paagla123 You can start thinking about what kind of content would help Users in this step.

**Comment by paweenwich** [comment]
If user doesn't have any campaign, why don't we redirect him/her to create campaign page in stead.  That page is catchy enough and he might have some idea.

**Comment by daver78** [comment]
@paweenwich That's a good idea!

@paagla123 What do you think?  Do you see something specific that could go in this area on the home page, or should we try @paweenwich's idea?

**Comment by coa0329** [comment]
Should we redirect them to setting first, so they can enter the company information ?

**Comment by daver78** [comment]
@coa0329 Yes; I envision they will have gone through a short set-up wizard in advance of hitting this screen.  Haven't created it yet, but definitely need to.

**Comment by daver78** [comment]
@paagla123 I'm closing this.  If you find an issue with a virgin user, create new Issue.
