### ISSUE TITLE
[PABP] New Email UI needs to show the right "Day"

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#170]
In the left listing of Emails, the 'x' in "Day x" should be based on the schedule set by the User.  Currently, it is hardcoded.

**Comment by paagla123** [comment]
![image](https://user-images.githubusercontent.com/29718335/32011354-62ad42b0-b969-11e7-9c68-f651d3aa6a34.png)

**Comment by paagla123** [comment]
Superceded by #190 . I am closing this one.
