### ISSUE TITLE
[Form Builder] Give "Settings" modal some love

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#178]
Dave you lazy a** bastard, fix this please:

![image](https://user-images.githubusercontent.com/7561473/32016040-b8af9a06-b977-11e7-88ae-e83bcad3d887.png)

**Comment by daver78** [comment]
Modified to the following:

![image](https://user-images.githubusercontent.com/7561473/32124450-a8d9905e-bb1c-11e7-8486-b7a8c0415cae.png)

@paagla123 Please close once checked.

**Comment by daver78** [comment]
@paagla123 This is a case where there are two HTMLs that do almost the same thing.  I only applied this to `FormEditorEdit.html`, not `FormEditorNew.html`.  

Can you see if we want to refactor this and combine into one HTML?  Not sure who worked on it.

**Comment by paagla123** [comment]
@coa0329 do we need to discuss this or is @AumpaiFung going to handle?

**Comment by coa0329** [comment]
@AumpaiFung  will.

**Comment by AumpaiFung** [comment]
@daver78  - Both pages are in use, and I will change it, follow your prototype.

**Comment by AumpaiFung** [comment]
@daver78  @paagla123  Stage done.

**Comment by paagla123** [comment]
@AumpaiFung thank you.
