### ISSUE TITLE
[UI] Add easy way to switch between sub-accounts

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#18]
As we know from Studio Users (and our own personal use), it is a PITA to switch sub-accounts.

Let's put that in the past for good.

**Comment by daver78** [comment]
Quick working example for now:

![image](https://user-images.githubusercontent.com/7561473/30671219-9df304c8-9e1a-11e7-8def-04e79e1db156.png)

@paweenwich What's the best way to carry this out across all pages?  I see that you've started to externalize the angular js for each page.  If I'm not mistaken angular can only bootstrap one `ng-app` per html document, so copying this code (which I mostly copied from the login page) into each `js` isn't efficient.

Can you think of an easier way to accomplish this goal?

**Comment by daver78** [comment]
@paagla123 Take a look this one it is on staging and see what you think.  It's not currently using `angular-chosen` like the login page, but we can probably do that here too.  "Feel " it and see what you think we should do.

**Comment by paweenwich** [comment]
@daver78  I don't have a clear idea why user need to switch sub account.  If we target this app to entry level user, how come this user have multiple sub account.  

I think we need to make the checklogin/login code in to angular.service in order to prevent copy and paste.  Will research on that, never try before :)

**Comment by paweenwich** [comment]
@daver78 I comment out this for now, because it makes others page beside (welcome.php) fail due to missing seemlessloginCtrl  code.

**Comment by daver78** [comment]
@paweenwich Thank you for commenting it out.  That occurred to me after I checked in but it seemed to be working.  

Regarding why we need this, we are getting more interest from our existing Clients (service providers), who each have multiple Clients that they want to run campaigns for via DV.  For this reason, I'm thinking ahead to making their life easy to switch between multiple accounts.

Make sense?

**Comment by paweenwich** [comment]
OK

**Comment by paweenwich** [comment]
@daver78 I end up create davinci module with that component.   Please see js/angular-davinci.js  
so, the new directive <accountSwitch> will create the switch account UI.   To use this, the app need to inject 'davinci' module.  Right now only welcome.php and audience.php inject the module.  

you can change ui by change "accountSwitch.html"

**Comment by daver78** [comment]
@paweenwich Excellent.  I will create a separate task for each section's developer to inject this into their module.

I will take a look at your template, too.

Great work!

**Comment by daver78** [comment]
@paweenwich Can you have someone use the same `chosen` style that we use on the login page?

**Comment by daver78** [comment]
@paagla123 and @paweenwich I'm closing this since I did it.
