### ISSUE TITLE
[REPORTING] API's required for Reporting

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#180]
Query for individual email summary
@amalekshahi  https://studio.dashboard.mdl.io/api/Report//GetAdminReportData?rn=allprogram_allemail_detail&si=0&ai=679&st=0&fd=01/01/2017&td=08/29/2017&seed=false&datasourceType=redshift
This is existing and should remain unchanged. I don;t believe the dashboard is recording the custom unsubscribes - any thoughts on that?
@coa0329  please include Delivered in a new column between Sent and Opened on the main campaign page. Also - please only show elements that start with "Email" and not the rest.

Query for Email Summary
@amalekshahi  please create a new end point that returns aggregate stats for all emails, consider all element names starting with "Email". Pl consider unique aggregate.
@coa0329  this will be used for the graph representing the funnel when you click on View More Performance Reports

Drill down to contact detail
@amalekshahi  we now need drill down reports (end points) when someone clicks on any of the numbers. 
@coa0329  we will display them in the same format as audience display using data tables

**Comment by paagla123** [comment]
@amalekshahi please also provide an endpoint to get page, no of unique visits, submits, clicks on external links for each page in the microsite. Pl ask if any questions.

**Comment by amalekshahi** [comment]
- Query for individual email summary: What do you mean by the custom unsubscribes
- Query for Email Summary: Is the difference between summary and detail report just the omission of program name?
- Drill down to contact detail: Please talk to Amir/ Aref about this. This is their endpoint
- Authentication: The endpoint that I provided was just a backdoor for your use and shouldn't be used in a production environment. You should use a different endpoint and pass token each time. Are you familiar with this approach?
- MS endpoint: Is this a new report? If so, please list all the columns that you need

**Comment by daver78** [comment]
@paagla123 I think that in general, you're on the right track here.  Sounds like you need to clarify @amalekshahi's questions.  

The only difference I would have employed in the spec is showing what I'd like the JSON columns/data to look like to make Ali's job easier & more clear, and perhaps enable @coa0329 to complete those sections w/mocks.

The only yellow-flag I see above is the endpoint for Promote a Blog Post (microsite) report, where you ask for # of unique visits.  Are we going to have a problem with that?

**Comment by paagla123** [comment]
@amalekshahi here're answers to your questions.
However, first of all, the team has requested that we pass program id along with the account id so that we only get back data related to the specific program. Current call is:
https://studio.dashboard.mdl.io/api/Report//GetAdminReportData?rn=allprogram_allemail_detail&si=0&ai=228&st=0&fd=08/28/2017&td=08/31/2017&seed=false&datasourceType=redshift 
We would like to add program_id to it.
Now for your questions.

- Query for individual email summary: What do you mean by the custom unsubscribes: 
KD>> This is something many clients, including  MindFire ourselves, use. Instead of using the standard unsubscribe link from Studio, they send people to another page where  a Javascript runs to execute a custom unsubscribe. An example may be, I want to unsubscribe from Blogs but not from eBooks
- Query for Email Summary: Is the difference between summary and detail report just the omission of program name?
KD>> No. This aggregates all elements across the program. The element name MUST start with the letters "Email". Pl call if this is not clear.
- Drill down to contact detail: Please talk to Amir/ Aref about this. This is their endpoint
KD>> OK. I will leave this with @javpowell for now.
- Authentication: The endpoint that I provided was just a backdoor for your use and shouldn't be used in a production environment. You should use a different endpoint and pass token each time. Are you familiar with this approach?
KD>> Sure. Aren't we already doing this for Studio API's? I assume the Ttoken with RedShift will be different - right?
- MS endpoint: Is this a new report? If so, please list all the columns that you need
KD>> What's this?

**Comment by amalekshahi** [comment]
allprogram_allemail_detail report: I added an optional Program_ID filter to this report and changed it such a way that it only shows emails that start with "Email" in their name. If you pass Program_ID to ##si##, the report will show only rows for that program otherwise if ##si## is zero, it will show all programs.

**Comment by amalekshahi** [comment]
I added summary report. You can use the same endpoint to test it:
https://studio.dashboard.mdl.io/api/Report//GetAdminReportData?rn=allprogram_allemail_summary&si=0&ai=228&st=0&fd=8/01/2017&td=10/30/2017&seed=false&datasourceType=redshift
This report uses the same filters (account_ID, OPTIONAL program_ID and Email name filters)

**Comment by amalekshahi** [comment]
Regarding authentication: We are going to close this backdoor (access queries without authentication) soon. Please use Fiddler with our standard dashboard to understand how to authenticate and pass tokens to access the assets ASAP

**Comment by paagla123** [comment]
@amalekshahi thank you very much. We will test it today and respond. Please do not close the backdoor this week - let us test and then we will put the code in place with the authentication by end of the week. You can close the backdoor next week, if that's ok.
@coa0329 pl see here - we can discuss at the meeting this afternoon.

**Comment by coa0329** [comment]
@amalekshahi @paagla123 

I can pass the token to your api. You can close the backdoor.

**Comment by coa0329** [comment]
@paagla123 

I add Delivered column.

**Comment by paagla123** [comment]
@amalekshahi for the summary report, we need only one record returned, which should be the summary of all emails. It should be the combined activities across all emails.
@daver78 does that make sense to you?

**Comment by amalekshahi** [comment]
Done. Summary report is changed to include the grand total of unique contacts.

**Comment by paagla123** [comment]
@amalekshahi thank you. You've been awesome help.
I will test and let you know if I have any questions/comments.

**Comment by coa0329** [comment]
@paagla123 

I show data from the summary in PERFORMANCE REPORTS.
