### ISSUE TITLE
PII passed in query string?

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#182]
@paagla123, I see what I think is PII passed in the query string as I view activity from the email you sent for Mac's blog:

![image](https://user-images.githubusercontent.com/7561473/32200107-366b4c74-bd8d-11e7-8ab6-ca6b11e1d45e.png)

Can you check w/team to see if are passing the email address in the query string?

**Comment by daver78** [comment]
@paagla123 Here's an example of a full link with PII passed to GA:

`http://www.mindfirestudio.com/blog/video-october-economic-webinar-same-ol-same-ol-and-more/?campaignID=dffb7af45eee08a6ab70be4489d89a5a&contactID=94086&source=EMAIL1&utm_source=Email&utm_medium=Email&utm_campaign=BlogPromotion&utm_term=WTTOctober&utm_content=Button&t=&e=mschroeder@inwk.com&h=1c2ad484`

**Comment by coa0329** [comment]
@daver78 

http://www.mindfirestudio.com/blog/video-october-economic-webinar-same-ol-same-ol-and-more/?campaignID=dffb7af45eee08a6ab70be4489d89a5a&contactID=94086&source=EMAIL1&utm_source=Email&utm_medium=Email&utm_campaign=BlogPromotion&utm_term=WTTOctober&utm_content=Button&t=&e=mschroeder@inwk.com&h=1c2ad484

Is this the correct link that you want ?

**Comment by paagla123** [comment]
@coa0329 @daver78 this was initial part of the plan for the conversion tracking, which I guess we never changed in the code. @coa0329 we should not send email in URL - Google will block it. What are t & h?
In any case, this will now get replaced with Studio's own tracking - so we will have to change this part of the code anyway.

**Comment by coa0329** [comment]
@paagla123 

Those links with email are not from davinci. We don't put email in it.

These are the parameter davinci put in the link

campaignID={{campaignID}}&contactID=##id##&source=EMAIL1&{{URL-BLOG-POST-UTM}}

**Comment by paagla123** [comment]
@daver78 I looked at the links DaVinci is creating - and the dashboard. None of the 3 contacts (last 3 in your screenshot) opened the emails, per dashboard. So where are these page visits coming from?

**Comment by paagla123** [comment]
Based on the findings so far, I am closing this one - @daver78 and @coa0329 .
We will reopen if this crops up again.
