### ISSUE TITLE
[PABP] Allow users to download the html for the emails they create

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#187]
Per discussions with @paweenwich  and @daver78 , we need to add a download button in the screen where the emails are saved. The download button should be clickable after the emails are saved, and will download the html to the user's local drive for use elsewhere, e.g., with Studio. @daver78 will help define the UI modification initially, and then we will assign to @jiewsone to implement.

**Comment by daver78** [comment]
@paagla123 For now, what do you think of this:

![image](https://user-images.githubusercontent.com/7561473/32350878-da54ccd2-bfd8-11e7-8aa8-a146464d44ed.png)

... and then once clicked, you see this:

![image](https://user-images.githubusercontent.com/7561473/32350881-dc95ca00-bfd8-11e7-87de-6fb5bc97aa23.png)

Do you think we do both of these by T-day, or just download the HTML?

**Comment by paweenwich** [comment]
@paagla123 Done.  same as #188

**Comment by paagla123** [comment]
@paweenwich - sorry - #187 and #188 are different, one for Blog and one for eBook.  #188 includes download for landing pages.
When you say done, what is it that you refer to?
Download works for Blog, so I will close #187. I will close #188 after testing eBook. Thx
