### ISSUE TITLE
[PABP] When the logo and color in settings are changed, the email does not pick it up

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#189]
This happens even if the email has not been created - as long as the campaign was saved. Steps to recreate:
1) Start a new blog campaign
2) Type in a blog URL and save (do not create email)
3) Go to settings and change logo, button color, address, phone.
4) Open campaign and create new email.
RESULT: Email uses new address and phone but old logo and button color.
If you create a new campaign at this time, it uses new color and logo.

**Comment by paweenwich** [comment]
@paagla123 Done
