### ISSUE TITLE
[PABP] Email schedule Header is ONE day short

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#190]
See screenshots below - should be self-explanatory
![image](https://user-images.githubusercontent.com/29718335/32260417-fdfd8638-be84-11e7-8d74-b4ed192030da.png)
See the problem caused here: Day 1 and then Day 0
![image](https://user-images.githubusercontent.com/29718335/32260435-20f8eb96-be85-11e7-8ddf-1b2fcd6d034f.png)

For 3rd email, we need to add the number of days selected to the Day No in the 2nd email. See screenshot be;low:
![image](https://user-images.githubusercontent.com/29718335/32260590-086326e0-be86-11e7-9481-3fcdee09162e.png)

**Comment by jiewsone** [comment]
@paagla123 Fixed on stage.
