### ISSUE TITLE
[PABP] Test All Emails in Sequence still not working

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#191]
We should only display audiences with 10 contacts or less and launch the campaign based on test schedule selected.

See screenshot below:
![image](https://user-images.githubusercontent.com/29718335/32260625-4ea63502-be86-11e7-8589-a09e38407e62.png)

**Comment by coa0329** [comment]
@paagla123 @jiewsone 

We should have the checkbox in audience to check to show that list in that dropdown.

**Comment by paagla123** [comment]
@coa0329 I told @jiewsone that he should show only audiences with <=10 members in the dropdown. Does that not work? I want to minimize the need for checkboxes etc.

**Comment by jiewsone** [comment]
@paagla123 Fixed on stage.

**Comment by paagla123** [comment]
@jiewsone great work - love what you have done. Two issues still remaining, after testing.
1) You have used a target audience sendTestList that is not defined in the MAML. @coa0329 are you able to add this to the template?
2) I scheduled only emails 1 and 2. However, in the published MAML you have scheduled emails 2 & 3, and email 1 was actually scheduled in the past. @jiewsone please address this.

**Comment by coa0329** [comment]
@paagla123 

target audience sendTestList is in the MAML v12.

![051](https://user-images.githubusercontent.com/7914690/32423800-5088ca66-c2db-11e7-9905-d756a569bbf2.JPG)

===========

@coa0329 I told @jiewsone that he should show only audiences with <=10 members in the dropdown. Does that not work? I want to minimize the need for checkboxes etc.

If you use those lists in send test, Will they count in the report too ?

**Comment by paagla123** [comment]
@coa0329 my fault - I did not see the seedList because it was below. YES IT WORKS - YEAH!

@jiewsone only one bug left now. I had set up emails 1 & 2, send test list sent me emails 2 & 3.

@coa0329 re test list, it is showing correct - I only see lists with small numbers. @jiewsone has done good work here. Thanks

**Comment by coa0329** [comment]
@paagla123 

For report : 
Can we ask Ali to exclude data that send to TargetAudiences "sendTestList" [Id="41"] ?

**Comment by paagla123** [comment]
@coa0329 yes we can. However, the schedule id will change from time to time, and there will be a separate test schedule id for each of the emails. Can we send him an array of schedule ids that we want to exclude? Thanks

**Comment by coa0329** [comment]
@paagla123 

![054](https://user-images.githubusercontent.com/7914690/32425091-350b1f02-c2e3-11e7-9c40-2a873c34edc0.JPG)

All test emails will send to TargetAudiences "sendTestList". 
So it should be easier to filter with the condition TargetAudiences not "sendTestList" [Id!="41"].

**Comment by paagla123** [comment]
@coa0329 what's the ID=41? Who's ID is that?

**Comment by coa0329** [comment]
@paagla123 

The id of TargetAudiences "sendTestList"

![055](https://user-images.githubusercontent.com/7914690/32425216-0ed8d2b0-c2e4-11e7-83bf-5ac71f4a0f3f.JPG)

![056](https://user-images.githubusercontent.com/7914690/32425226-23126692-c2e4-11e7-9466-2e60e1076d5f.JPG)

**Comment by paagla123** [comment]
@coa0329 OK thanks, I will ask.

**Comment by jiewsone** [comment]
@paagla123 
"@jiewsone only one bug left now. I had set up emails 1 & 2, send test list sent me emails 2 & 3." 
Fixed on stage.

**Comment by paagla123** [comment]
@jiewsone I think the issue is that you are undoing changes instead of publish, once you have published the first schedule for test. And therefore no subsequent schedule gets published.
![image](https://user-images.githubusercontent.com/29718335/32450425-07a80d6e-c2c9-11e7-978b-a506ad74dcb4.png)

**Comment by jiewsone** [comment]
@paagla123 
I already fix bug "Undid Changes" publish in case Davinci cannot save to CouchDB then it's publish the old version to studio.

But "Undid Changes" publish can happen if you change Email Field (Email Subject, Email Content, ...) only because all email fields are the URL link to S3 then it's not change anything in Studio.

PS. Do you see the new button "Send All Emails"? You have to click it if you need to send test all emails.
