### ISSUE TITLE
[PABP] Toggle Alerts (#3 in accordion)  does not turn green even when saved, turns green only after Schedule Broadcast (#4) turns green

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#192]
Pl see screenshot below. #3 has been saved, but nit green yet, It will turn green only after #4 is saved.
![image](https://user-images.githubusercontent.com/29718335/32260777-4647a6a6-be87-11e7-9822-d4f995612fef.png)

**Comment by coa0329** [comment]
@paagla123 

User may not want any trigger so we will change step3 to green when user save step2.

**Comment by jiewsone** [comment]
@paagla123 Fixed on stage.
