### ISSUE TITLE
[Welcome] Seems we have a $rootScope:infdig issue; why?

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#20]
For some reason, I see a `$rootScope:infdig` error on this page.  What the F&$K is that kind of error name??

**Comment by daver78** [comment]
To resolve this for now, I changed the code to return 1 instead of a random number.  Anyways, we're soon going to need to replace this with the real data.

![image](https://user-images.githubusercontent.com/7561473/30671392-8368e61c-9e1b-11e7-9a87-9b95f40cdc77.png)

**Comment by daver78** [comment]
@paweenwich FYI!

**Comment by paweenwich** [comment]
I have no idea either.  (From google 
infdig  = Infinite $digest Loop)

**Comment by daver78** [comment]
@paweenwich Yes, basically like a loop that consumes too many resources to Angular kills it to keep the browser from crashing.

**Comment by daver78** [comment]
@paweenwich I'll close this.
