### ISSUE TITLE
[Welcome] Fix spacing so that if possible, we have room for a what's new msg

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#200]

**Comment by daver78** [comment]
@paagla123, made the following adjustments seen here:
![image](https://user-images.githubusercontent.com/7561473/32303098-a4ee28a0-bf23-11e7-84f0-83dd3e5c7f1b.png)

**Comment by coa0329** [comment]
@paagla123  

What do you want me to do in this issue ?

**Comment by paagla123** [comment]
@coa0329 Fix whatever spacing @daver78 wants to fix

**Comment by coa0329** [comment]
@paagla123 

I think @daver78 already did that.

**Comment by daver78** [comment]
No action required. I already checked in.

**Comment by daver78** [comment]
@paagla123 Unless you see something else required here, we can close for now.

**Comment by paagla123** [comment]
@daver78 closing for now, but we need to discuss at some point who will create and populate this content on a regular basis. I believe this cannot be static content - needs to be changed periodically.

**Comment by daver78** [comment]
@paagla123 Agreed.  Should change with every release.

**Comment by paagla123** [comment]
@daver78 while I agree we should change WHat's New with every release, I also see an opportunity to add Tip of the Day and change that almost on a daily basis. Should we consider adding a UI here to use internally for this purpose?

**Comment by daver78** [comment]
@paagla123 Excellent idea, love the way you're thinking.  Easy to add a list of these in couchDB, then use angularjs to pick a random one and display it.

Is that OK, or do we want everyone to see the same tip at the same time?

**Comment by paagla123** [comment]
@daver78 randomize better

**Comment by daver78** [comment]
Ok. Create issue and let's backlog so we don't forget?

**Comment by paagla123** [comment]
Done
