### ISSUE TITLE
Add Amir to github repo

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#201]
@coa0329 Please add: `manoochehr45`

**Comment by coa0329** [comment]
@daver78 @manoochehr45
I send invite to manoochehr45.

**Comment by daver78** [comment]
@coa0329 Thank you.  @manoochehr45 Welcome to the dark side :)

**Comment by manoochehr45** [comment]
Thank you all. happy to join the team on the dark side.
