### ISSUE TITLE
[Settings] Comment out sub-accounts for now

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#204]

**Comment by daver78** [comment]
@paagla123 I did this.  Shall we close for now?

**Comment by paagla123** [comment]
@daver78 where are these sub accounts. I am Confucius!

**Comment by paagla123** [comment]
@daver78 we can close provided you tell me where these sub accounts were that you commented out?

**Comment by daver78** [comment]
@paagla123 Did I misunderstand you when you asked me to comment them out?

![image](https://user-images.githubusercontent.com/7561473/32425671-cd6269ec-c269-11e7-93ce-477dde828134.png)

**Comment by paagla123** [comment]
@daver78 that one - yes its ok. Thanks
