### ISSUE TITLE
style.css not updated?

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#207]
On staging, I can tell that `style.css` was not updated.  Not sure how it wouldn't be included if you're pulling from git, but I can tell given that the "Delivered" section is missing the `bg-color`.

![image](https://user-images.githubusercontent.com/7561473/32344569-8fba4d0a-bfc4-11e7-9181-d4437484b196.png)

Please check `style.css` to make sure:
```
.green-bg,
.bg-info {
  background-color: #007A00;
  color: #ffffff;
}
```

... is there.

**Comment by coa0329** [comment]
@daver78 

Do you fix it ? I see it show in green.

**Comment by daver78** [comment]
@coa0329 No, I didn't do anything.  Where do you see green?  On staging??

**Comment by coa0329** [comment]
Yes on staging.

![047](https://user-images.githubusercontent.com/7914690/32359820-27e6b33e-c083-11e7-8107-d4763f5cbdc6.JPG)

**Comment by daver78** [comment]
@coa0329 So strange!  Old css must be cached for me.  We'll close for now!
