### ISSUE TITLE
[Database] Create Billing Profile for Google SQL Cloud

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#209]
@javpowell please get together with Baker and have him input the credit card here. Thanks for your help. You are assigned to the project owner role, so you should be able to log in to your Mindfire acct and do it. @daver78 FYI.
Go To http://console.cloud.google.com , select daVinci from dropdown, then go to Billing. See screenshot below. Thanks
![image](https://user-images.githubusercontent.com/29718335/32368691-3615ceb4-c0b9-11e7-8cee-f60b4e580828.png)

**Comment by javpowell** [comment]
@paagla123 @daver78 I don't seem to have access to do this:

https://www.screencast.com/t/u87uxRoL

**Comment by paagla123** [comment]
@javpowell you are most certainly assigned. Pl select mindfiremail.info org and you will see daVinci:
![image](https://user-images.githubusercontent.com/29718335/32415352-9cc54a92-c1ed-11e7-867e-223012bd44da.png)

**Comment by daver78** [comment]
@paagla123 and @javpowell This should be done.  The UI in that particular section is a little confusing, I think @javpowell may have missed it.

Anywho, I linked this project to the MindFire billing account we use in Google.

Please confirm this worked and then close this issue.

**Comment by paagla123** [comment]
Works. Thanks'
