### ISSUE TITLE
[Refactor] Research angular service

### ISSUE THREAD

**Issue by paweenwich** [coa0329/BhaangWeb#21]

**Comment by daver78** [comment]
@paweenwich Oops I created one for this too.  I'll kill mine.

**Comment by daver78** [comment]
@paagla123 and @paweenwich Do you still need this?

**Comment by daver78** [comment]
@paagla123 and @paweenwich I'm closing this since no response.

**Comment by paagla123** [comment]
@daver78 were ok thanks
