### ISSUE TITLE
[PAEB] Fix fugly alignment issue with "SUBJECT"

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#215]
![image](https://user-images.githubusercontent.com/7561473/32393907-8b1edd40-c098-11e7-8f14-f1015e9a8ffc.png)

What is this sh*t, Dave?  You're better than that.  C'mon!

**Comment by daver78** [comment]
![image](https://user-images.githubusercontent.com/7561473/32411289-592d5652-c194-11e7-9463-1d1eb9bbc38f.png)

@paagla123 I'm not sure if I did this or someone else, but I removed `style="white-space: nowrap;text-overflow: ellipsis;max-width: calc(100% - 275px);display: inline-block;overflow: hidden;` from the _x-editable_ thingsy.  Then I put a light rounded border around the section, and moved the "See Vars" button a little bit.

Is this OK for now?

**Comment by paagla123** [comment]
@daver78 cab't see this change yet in stage. @coa0329 can you please pull Dave's changes from weekend to stage  on Mon AM? Thx

**Comment by coa0329** [comment]
@daver78 @paagla123 

I pull the code to stage.

**Comment by paagla123** [comment]
Thanks. Closing this. Looks good. Thanks Dave
