### ISSUE TITLE
[PABP] See if Email 2 and 3 should use the scheduleID from Email 1?

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#216]
@paagla123 Yesterday I was thinking about the campaign you ran with @Mcfarsheed 2 weeks back.

I believe that Email #3 ended up having a larger number of targeted people because @Mcfarsheed ended up updating the database.  There's no problem with this and I'm sure it will happen in the wild all the time.

However, it made me think -- you were slightly confused by it, and it does seem odd that the 3rd email ends up having more targeted than Email #1 and 2.

Here's my thought: Should we be using the `scheduleID` from Email 1 in Email 2 and 3 in your TA filter, instead of how you're doing it now?  I assume you're not doing this now.

If you do this, then Email 2 and 3 will never be larger than Email 1.

Let me know thoughts.

_PS: That said, I can see people wanting to have the option to do it **both** ways ... but if we're trying to limit cognitive overload by diminishing the # of options to think about, not sure what seems most desirable._

**Comment by paagla123** [comment]
@daver78 I am not sure if there was anything wrong with what @Mcfarsheed did. Initially I though they had duplicated the records, but once she gave the proper explanation I am ok. So I think let's leave things the way they are - we can address this later if this comes up again.
