### ISSUE TITLE
[Settings] Hide Permissions in Add Users (and display) for now

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#219]
...for the Thxgiving release - seems we don't have time to deal with this - right?
I suggest we give all users ADMIN access - should be ok since no one is expected to log into Studio.

**Comment by daver78** [comment]
Yes let's hide the column and do as you suggest.

**Comment by paagla123** [comment]
@coa0329 who should this be assigned to?

**Comment by coa0329** [comment]
@paagla123 

Fixed on stage,
