### ISSUE TITLE
Fix the sort bug by using server time instead of browser time.

### ISSUE THREAD

**Issue by paweenwich** [coa0329/BhaangWeb#22]

**Comment by paweenwich** [comment]
Browser time cause uncontrollable behavior.  Change to server time.

**Comment by daver78** [comment]
@paweenwich and @paagla123 I think we've solved this for now.  I'll close it; you can re-open if I'm wrong.

**Comment by paagla123** [comment]
This works - I will observe

**Comment by daver78** [comment]
@paagla123 and @paweenwich HOORAY!
