### ISSUE TITLE
[SummerNotes] Deal with Table Icon - works Fugly!

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#220]
@daver78 I suggest we either hide the table icon from summer notes or give it some special love. The way it is right now, it will definitely bring up a lot of user issues.

**Comment by daver78** [comment]
Hide it! Assign?

**Comment by paagla123** [comment]
@jiewsone can you pl handle this? Thx

**Comment by coa0329** [comment]
@paweenwich  will hide it.

**Comment by paweenwich** [comment]
@paagla123 Done
