### ISSUE TITLE
Create Internal Domains for Blog Emails

### ISSUE THREAD

**Issue by coa0329** [coa0329/BhaangWeb#24]
_From @paagla123 on August 31, 2017 16:56_

This domain will be used to host the online version of the emails as well as the unsubscribe landing page. Not required for P17, but we cannot go to production without this.

_Copied from original issue: coa0329/Bhaang#53_

**Comment by coa0329** [comment]
_From @daver78 on August 31, 2017 20:12_

@paagla123 What are you asking me to do?  I'm OK with whatever generic domain we come up with.

**Comment by coa0329** [comment]
@paagla123 @daver78 @paweenwich 

We don't need the site for online version. We can save them on S3.

The current process, we will render the email, save it as html and upload it to S3 when user click save email.

We can save 2 html each time user click save  when user click save.
1 The html without view online in the content for view online. (We can use the same file name with suffix like _online in the filename)
2 The html with view online in the content. Then we put the link of #1 in it. 

Example.
For email1 of campaignid a3fbe4d26d00539cc0200035408a5377
1 We save the html without view online to https://s3-us-west-1.amazonaws.com/bkktest/tmp/TEXT-AREA-16916-a3fbe4d26d00539cc0200035408a5377-EMAIL1CONTENT_online.html
2 We add the link of #1 to view online link in the content then we save the html with email to https://s3-us-west-1.amazonaws.com/bkktest/tmp/TEXT-AREA-16916-a3fbe4d26d00539cc0200035408a5377-EMAIL1CONTENT.html

**Comment by coa0329** [comment]
_From @daver78 on September 4, 2017 3:20_

@coa0329 You can't use this technique because `https://s3-us-west-1.amazonaws.com/bkktest/tmp/TEXT-AREA-16916-a3fbe4d26d00539cc0200035408a5377-EMAIL1CONTENT.html` will not personalize variables like `##firstname##`.

This is why the Microsite is useful; we can use the HTML we've saved to S3 inside a Microsite page, which gains us personalization.

Does that make sense?

**Comment by coa0329** [comment]
ok. I got it.

**Comment by coa0329** [comment]
@daver78 @paagla123 

We save 2 versions of the html on S3. (with and without view online link)

We create the mircosite in the maml. We set the domain to davinci.m.mdl.io.
When user launch the program
1 We will automatically add sub domain to the microsite using _id from davinci. Example 583deefb2ba32388e98a4d82b4740faa

2 We will add the ##purl##, domain and emailX.html in the link in email content. Example http://##purl##.davinci.m.mdl.io/583deefb2ba32388e98a4d82b4740faa/EmailX.html

In each html in microsite we put the new set of variables ##emailXcontentonline## in EmailX.html. It will convert to the link on S3 for user to see the html without view online.

**Comment by coa0329** [comment]
_From @daver78 on September 4, 2017 14:41_

@paagla123 Will you verify this?

**Comment by coa0329** [comment]
_From @paagla123 on September 4, 2017 14:47_

I tested - this does not appear to be done yet. @coa0329 please confirm.

**Comment by coa0329** [comment]
@paagla123 @daver78 Please Verify, Are you ok with this solution ?

**Comment by coa0329** [comment]
We cannot use the same domain for both account. We must add the account id to it.
The domain for campaignlauncher will be davinci228.m.mdl.io
The domain for davin ci will be davinci16916.m.mdl.io

**Comment by coa0329** [comment]
_From @daver78 on September 5, 2017 17:2_

@coa0329 This makes sense to me.  @paagla123 Do you agree?

**Comment by coa0329** [comment]
_From @daver78 on September 7, 2017 23:30_

@coa is this still open?

**Comment by coa0329** [comment]
@paagla123 said this will not include in Print17.

**Comment by coa0329** [comment]
_From @daver78 on September 8, 2017 5:20_

@paagla123 Was that intentional?  I see you moved it to MarTech milestone.

**Comment by coa0329** [comment]
@paweenwich 

We save 2 versions of the html on S3. (with and without view online link)

We create the mircosite in the maml. We set the domain to davinci{{acctID}}.m.mdl.io.
When user launch the program
1 We will automatically add sub domain to the microsite using {{progID}} from davinci. 

2 We will add the ##purl##, domain and emailX.html in the link in email content. Example http://##purl##.davinci{{acctID}}.m.mdl.io/{{progID}}/EmailX.html

In each html in microsite we put the new set of variables ##emailXcontentonline## in EmailX.html. It will convert to the link on S3 for user to see the html without view online.

In TMAML save the link to s3 for each email content without view online link to {{URL TEXT-LINE-ACCTID-PROGRAMID-EMAILXCONTENT-ONLINE}}

**Comment by coa0329** [comment]
@paweenwich 

We save 2 versions of the html on S3. (with and without view online link)

We create the mircosite in the maml. We set the domain to davinci{{acctID}}.m.mdl.io.
When user launch the program
1 We will automatically add sub domain to the microsite using {{progID}} from davinci.

2 We will add the ##purl##, domain and emailX.html in the link in email content. Example http://##purl##.davinci{{acctID}}.m.mdl.io/{{progID}}/EmailX.html

In each html in microsite we put the new set of variables ##emailXcontentonline## in EmailX.html. It will convert to the link on S3 for user to see the html without view online.

In TMAML save the link to s3 for each email content without view online link to {{URL TEXT-LINE-ACCTID-PROGRAMID-EMAILXCONTENT-ONLINE}}

============

@paagla123 
Should we have the same microsite for view online in ebook template too ?

============

**Comment by paagla123** [comment]
@daver78 @paweenwich yes I believe so

**Comment by coa0329** [comment]
Please goto campaign coatest-blog-092104 in Davinci studio. 

In Busines MicroSite.


Email3, I put the content of https://s3-us-west-1.amazonaws.com/bkktest/tmp/tests3.html in the variable email1contentonline.
Email3 can show the page correctly.
You can test at http://coatest901.davinci16916.m.mdl.io/21e0a8487d1f66b365b9d664ac04b2d1/Email3.html
![147](https://user-images.githubusercontent.com/7914690/30687276-fcfa82aa-9ee4-11e7-9e20-6812d4d51cc6.JPG)



Email1, I put ##URL SRC="https://s3-us-west-1.amazonaws.com/bkktest/tmp/tests3.html"## in the variable email1contentonline.
Email1 doesn't show. 
You can test at http://coatest901.davinci16916.m.mdl.io/21e0a8487d1f66b365b9d664ac04b2d1/Email1.html
![146](https://user-images.githubusercontent.com/7914690/30687279-00d3e8bc-9ee5-11e7-88c3-474857b66323.JPG)


Please let me know if I set something wrong ?
I need to use the link set in Email1 to show the page.

**Comment by daver78** [comment]
@paagla123 You got this?

**Comment by paagla123** [comment]
@daver78 yes

**Comment by paagla123** [comment]
This is fixed and closed
