### ISSUE TITLE
[Microsite] Settings Requirements

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#27]
With respect to this UI:
![image](https://user-images.githubusercontent.com/7561473/30703257-0aa9b84e-9ea4-11e7-80ba-6b011266ecd5.png)
... here's the meaning of each item as originally discuss with @paagla123: 

**Welcome Page URL**: Displays the entire URL of the Welcome Page.  `Copy URL` puts in your clipboard.  `Open in New Window` opens the URL in a new window.

**Thank-You Page URL**: Same as above.

**Landing Page Domain**: Shows 2 or 3 generic-ish domains that we’ve purchased for people to chose from.  @paagla123 will buy them and register them with Studio.  By default, when you create an eBook, we should use one of them without requiring the User to do anything.

**Buy my own domain for $11 p/year**: Eventually, we want people to be able to buy domains directly via the UI.  For now, we can modify the label on the button to say “I want to buy my own domain” and use it to display a modal with instructions on how to acquire and point your own domain.

**Meta Title**: I don't want this displayed to the User (at least for now; maybe later we will let them edit their meta tags).  The reason I displayed in the UI is to remind you of a few things:

a) Within the microsite’s HTML, we need to populate all the usual meta tags for the user.  The <title> should be the name of the eBook as set in Step 1.

b) I’m not sure how well Studio Microsites do with Facebook and other sharing sites.  Do we show the information appropriately?  

Meaning, if you take the URL to a Studio Microsite and try to share it on Facebook, Twitter, LI, etc., will the social sites pull the appropriate tags from the page?  I believe that because of how Studio does its redirects, there is an issue.  When I mentioned this to @paagla123, he said, "_Of course it works!_" -- but I'm not entirely sure :)  We need to double check.  

If it doesn't work, we can do a workaround.

**Comment by paagla123** [comment]
@coa0329 @jiewsone pl see this explanation for microsite domain for eBooks

**Comment by daver78** [comment]
@paagla123 I'm closing this.
