### ISSUE TITLE
[UI] Things to do to help 1st time Users

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#29]
- PABP: “Complete my call to action” should only display if the User has set something for this in Step 1.
- Change CREATE A CAMPAIGN button to CREATE YOUR FIRST CAMPAIGN
- Fix the `<a href>` in the box at bottom
- PABP: Comment out PAUSE CAMPAIGN until we decide what to do
- PABP: When editing subject, remove “Trash”
- PABP: When editing subject, form field needs to be wider. 
- PABP: Change Upload new image tooltip to “I’ll upload and replace the image in your email”
- PABP: Add something that says “Wondering how to change the fixed areas? They’re in your settings”
- PABP: Orange button for Email is confusing (in schedule)

**Comment by paagla123** [comment]
@daver78 videos
