### ISSUE TITLE
Warning: file_get_contents(conf/davinci.json): failed to open stream: No such file or directory in /home/cabox/workspace/html/admin/commonUtil.php on line 23

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#3]
When accessing DV on my local dev machine ([http://da-vinci-core-daver438618.codeanyapp.com/admin/](http://da-vinci-core-daver438618.codeanyapp.com/admin/)), I see this error message:

![image](https://user-images.githubusercontent.com/7561473/30517783-755da666-9b1e-11e7-9924-d79fb29f09d3.png)

I pulled this code from the `stage` branch.  Did someone forget to add and commit `conf/davinci.json` to this branch?

**Comment by coa0329** [comment]
This is the config file for stage, so we exclude it from git.

I cannot upload here so I will email it to you. 
Coa.

**Comment by daver78** [comment]
@coa0329 OK I will add this manually.  Perhaps what you and @paweenwich are looking for is `gitignore` -- which is a file that specifies intentionally untracked files that Git should ignore.  Google that and see if that does what you need. 

Is that what you're looking for?

**Comment by paweenwich** [comment]
May be you can come out with better solution. 
As you know, I need to find a place to put config file (davinci.json) that php code can read and know that this code is running to which server (stage or prod or .. )   Prod and Stage will have different version of this file.  

So, I ask everyone to manually create this file on their server and put it in .gitignore (to prevent git from push/pull) to repo to prevent it from move to production when merge.   

This there a way to make same filename (different content) exist in master and stage branch and not get overwrite when we do merging?

**Comment by daver78** [comment]
@paweenwich How about when you load the `davinci.json` conf file, you look at which server you're running on (maybe you can tell from the URL that's being used), and then use that information to find the right data in the conf file.

The conf file could be structured like this:

```
{
  "serverConf": {
    "Production": [
      {
        "serverName": "prod-name",
        "databaseEndPoint": "prod-endpoint"
      },
      {
        "anotherOption": "value",
        "andAnother": "value"
      }
    ],
    "Staging": [
      {
        "serverName": "staging-name",
        "databaseEndPoint": "staging-endpoint"
      },
      {
        "anotherOption": "value",
        "andAnother": "value"
      }
    ]
  }
}
```

Would this work?  Then none of us have to worry about changing this file or `.gitignore`.  I assume there will be more conf-related stuff in the future so it can go in here divided by environment.

**Comment by daver78** [comment]
@paweenwich Does the idea above help at all?

**Comment by daver78** [comment]
@paweenwich Did the above idea help at all?  I'll close this issue for now.
