### ISSUE TITLE
[PABP: Step 3] If you haven't created any segments, the "Chose your audience" default text says “No results ma”

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#31]
Maybe it is trying to say "No results matching".  We should fix at some point.

![image](https://user-images.githubusercontent.com/7561473/30720105-09d7fe8a-9edb-11e7-8997-ff7572d3ef16.png)

**Comment by paagla123** [comment]
@AumpaiFung can you please fix this? Thx

**Comment by AumpaiFung** [comment]
Done.

**Comment by daver78** [comment]
@paagla123 I think that if you have yet to create a Segment, we should `ng-if == no segments` this section (meaning, they don't see "Choose Your Audience" and the input field on the right), and instead, show them something that leads them to create their first segment.

Thoughts?

**Comment by daver78** [comment]
@paagla123 This is waiting for your test still?

**Comment by paagla123** [comment]
@daver78 yes.

**Comment by daver78** [comment]
@paagla123 Is this still waiting on test?

**Comment by paagla123** [comment]
This is done - close!
