### ISSUE TITLE
[PABP: Step 2] Hero image should link to blog post URL when deployed

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#33]
I should be able to click the hero image and arrive at the blog post.  Make sure to pass the UTM params too.

**Comment by paagla123** [comment]
Hmmm - @daver78 what about in the eBook? Should it link to the landing page?

**Comment by daver78** [comment]
@paagla123 Yes, good call.

**Comment by paagla123** [comment]
@coa0329 can you please assign someone to do this?

**Comment by coa0329** [comment]
Fixed on stage.

Blog : Send user to blog post url with utm params.
eBook : Send user to the landing page.
