### ISSUE TITLE
[Audiences] First-time User Experience Modifications

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#34]
- If you don’t have any Contacts, we should hide the two tables we presently show and display something that helps you start.  I think the first step is learning to upload contacts, and that should be the only thing you see on the page (other than the jumbotron at top).
- If this is my first time uploading Contacts, I may want to learn how to do it without actually creating a CSV.  Provide me a sample CSV I can use.  
- Change tooltip to something more meaningful when you hover over the “Upload csv file to import”

**Comment by daver78** [comment]
@paagla123 Let me know if you agree before we do this.

**Comment by paagla123** [comment]
@daver78 we agree that we have to do something here. However, there are more first time issues than just this. My vision is that we will have little training videos for this part only at each of these sections. What do you say to that?

**Comment by daver78** [comment]
@paagla123 Not sure what you're asking ... but I agree that there are many first-time UX things to do, and also with videos.  Did I answer your question? :)

**Comment by daver78** [comment]
@paagla123 I'm closing this one for now.  If you still have a question, let me know.

**Comment by paagla123** [comment]
@daver78 ok
