### ISSUE TITLE
[PABP] Do we still need "LAUNCH"?

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#35]
I think I saw that you can apply the same process to this blueprint as PAEP.  If so, this Issue is to resolve this issue.

If not, this issue is to apply love to the button and process to make it intuitive.

**Comment by paagla123** [comment]
@paweenwich has a plan - it should be in yesterday's (9/20) Skype.

**Comment by daver78** [comment]
I'm closing this because I think we're handling it in #127.
