### ISSUE TITLE
[PABP: Step 2] New seed record doesn't appear in drop-down list

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#36]
As a new User (virgin Account), I tried to add someone to my seed list.  

I went through the pop-up process, but when the page refreshed there was nothing in the drop-down.

Bug?

![image](https://user-images.githubusercontent.com/7561473/30719955-877162ba-9eda-11e7-9be2-0a68022cd930.png)

**Comment by jiewsone** [comment]
Fixed on stage.
