### ISSUE TITLE
[PABP: Step 2] View Online Dumps HTML & Unsub Strategy

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#38]
- When I clicked “Email not display correctly?” from my inbox, loads page showing the HTML (meaning, the HTM is dumped to the screen).

- Unsubscribe is not linked to anything.  What is our strategy there?  I'm wondering if we need a "pretty" unsub page like we do for MindFire Master.  @paagla123 like to know your thoughts.

**Comment by daver78** [comment]
@paagla123 Is this still open?

**Comment by paagla123** [comment]
@daver78 unsubscribe is still open. Let me close this one and open a new one for unsubscribe
