### ISSUE TITLE
[Audiences] Upload Contacts doesn't do anything

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#40]
After I select a CSV to upload, the screen just sits there.  What should happen next?

**Comment by paagla123** [comment]
@daver78 not sure why you got the problem. I agree this needs a little luv. What you have to do now is to type in a import name and click on Import button. I think the system should pick an import name on its own and automatically start the import process without waiting for any more clicks or inputs from user. We can discuss f2f if you like.

**Comment by daver78** [comment]
@paagla123 Where do you enter the import name?

This is what I see:

![image](https://user-images.githubusercontent.com/7561473/30727748-2b6506d8-9f08-11e7-8d8b-946557cea2b5.png)

After I select a file, it sits on this screen.  Only happening for me?

**Comment by coa0329** [comment]
![148](https://user-images.githubusercontent.com/7914690/30727809-cdd2b99a-9f7d-11e7-8bc8-2e8ca41c72b2.JPG)

You may don't have the following folders in your machine.

/admin/import/contactFile
/admin/import/importFile
/admin/import/microsoft
/admin/import/google

**Comment by daver78** [comment]
@coa0329 I should if they're checked into branch `stage` in github.  Confirm?

**Comment by daver78** [comment]
@coa0329 Yes, I have:
![image](https://user-images.githubusercontent.com/7561473/30728055-47ad195a-9f0a-11e7-8cf7-7712f15bb106.png)

**Comment by coa0329** [comment]
![149](https://user-images.githubusercontent.com/7914690/30728453-7cfd850e-9f82-11e7-808a-70436442787a.JPG)


Please show me the response of doUploadFile.php from your browser.

**Comment by daver78** [comment]
@coa0329 Ah ha:

```
<b>Warning</b>:  copy(import/importFile/09222017-034352_DV-sample-upload-file - Sheet1.csv): failed to open stream: Permission denied in <b>/home/cabox/workspace/html/admin/doUploadFile.php</b> on line <b>44</b><br />
{"success":false,"message":"failed to copy \/tmp\/phpBg0mJ7 to import\/importFile\/09222017-034352_DV-sample-upload-file - Sheet1.csv...<br>"}
```
Should I `chmod 777` or something in that directory?

**Comment by coa0329** [comment]
Please try chmod 777.

**Comment by daver78** [comment]
@coa0329 Looks like it was a permissions issue in my dev env.  Closing.
