### ISSUE TITLE
Change w3 include to php include

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#42]
_From @paweenwich on September 15, 2017 7:30_

w3 include is slow and can not include script.   Need to change to php include

_Copied from original issue: coa0329/Bhaang#111_

**Comment by paagla123** [comment]
_From @daver78 on September 15, 2017 16:56_

@paweenwich Should we reconsider using `php include` and perhaps do it the angular way?  See also issue #97 "Refactor Backlog" for additional notes on this.

**Comment by daver78** [comment]
@paweenwich & @paagla123 Does this still need to be open?

**Comment by paagla123** [comment]
@paweenwich I think we can close it - right?
