### ISSUE TITLE
Create specs for a sign up process

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#43]
_From @paagla123 on September 12, 2017 2:14_

_Copied from original issue: coa0329/Bhaang#104_

**Comment by daver78** [comment]
@paagla123 Switching this back to you (you said you have some idea).

**Comment by paagla123** [comment]
DaVinci Main Screen, click on Get Started option
![image](https://user-images.githubusercontent.com/29718335/31154883-fd35d462-a85e-11e7-895e-d380340444d6.png)

Sign up with Google or Facebook or LinkedIn - or manually by inputting Company name, first and last names, email and choose a password.
The system should go through a email validation process first.
