### ISSUE TITLE
[Promote a Blog Post] Populate reporting snapshot on blueprint home page, and complete "View More" reporting view too 

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#46]
_From @paagla123 on August 30, 2017 6:57_

@paweenwich here it is:

The query has been published and you can access it using the below link:

https://studio.dashboard.mdl.io/api/Report//GetAdminReportData?rn=allprogram_allemail_detail&si=0&ai=679&st=0&fd=01/01/2017&td=08/29/2017&seed=false&datasourceType=redshift 

Change ai= to your account# and fd and td to your date filters. Note that this is an internal link. Please don't share with clients

_Copied from original issue: coa0329/Bhaang#38_

**Comment by paagla123** [comment]
I ran the following query:
https://studio.dashboard.mdl.io/api/Report//GetAdminReportData?rn=allprogram_allemail_detail&si=0&ai=228&st=0&fd=08/28/2017&td=08/31/2017&seed=false&datasourceType=redshift

228 is CampaignLauncher

Got this JSON:
[
  {
    "Program": "Moe",
    "Email": "Email1",
    "Sent": 17,
    "Delivered": 4,
    "Opened": 0,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 0,
    "SoftBounced": 1,
    "Suppressed": 12,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "Rattlesnake Sausage",
    "Email": "Email1",
    "Sent": 4,
    "Delivered": 2,
    "Opened": 1,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 1,
    "SoftBounced": 0,
    "Suppressed": 1,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "Stuffed Omelette",
    "Email": "Email1",
    "Sent": 4,
    "Delivered": 2,
    "Opened": 1,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 1,
    "SoftBounced": 0,
    "Suppressed": 1,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "Stuffed Omelette",
    "Email": "Email2",
    "Sent": 13,
    "Delivered": 0,
    "Opened": 0,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 0,
    "SoftBounced": 0,
    "Suppressed": 0,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "Test",
    "Email": "Email1",
    "Sent": 16,
    "Delivered": 3,
    "Opened": 0,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 1,
    "SoftBounced": 0,
    "Suppressed": 12,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "coatest082502",
    "Email": "Email1",
    "Sent": 0,
    "Delivered": 0,
    "Opened": 1,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 0,
    "SoftBounced": 0,
    "Suppressed": 0,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "coatest082511",
    "Email": "Email2",
    "Sent": 3,
    "Delivered": 0,
    "Opened": 0,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 0,
    "SoftBounced": 0,
    "Suppressed": 0,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "coatest082513",
    "Email": "Email2",
    "Sent": 3,
    "Delivered": 0,
    "Opened": 0,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 0,
    "SoftBounced": 0,
    "Suppressed": 0,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "coatest082513",
    "Email": "OpenAlertLeadTrigger",
    "Sent": 1,
    "Delivered": 0,
    "Opened": 0,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 0,
    "SoftBounced": 0,
    "Suppressed": 0,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "coatest082514",
    "Email": "Email2",
    "Sent": 3,
    "Delivered": 0,
    "Opened": 0,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 0,
    "SoftBounced": 0,
    "Suppressed": 0,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "coatest082515",
    "Email": "Email2",
    "Sent": 3,
    "Delivered": 0,
    "Opened": 0,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 0,
    "SoftBounced": 0,
    "Suppressed": 0,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "coatest082515",
    "Email": "OpenAlertLeadTrigger",
    "Sent": 1,
    "Delivered": 0,
    "Opened": 0,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 0,
    "SoftBounced": 0,
    "Suppressed": 0,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "coatest082516",
    "Email": "Email1",
    "Sent": 0,
    "Delivered": 0,
    "Opened": 1,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 0,
    "SoftBounced": 0,
    "Suppressed": 0,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "coatest082516",
    "Email": "Email2",
    "Sent": 3,
    "Delivered": 0,
    "Opened": 0,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 0,
    "SoftBounced": 0,
    "Suppressed": 0,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "coatest082517",
    "Email": "Email2",
    "Sent": 3,
    "Delivered": 0,
    "Opened": 0,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 0,
    "SoftBounced": 0,
    "Suppressed": 0,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "coatest082521",
    "Email": "Email2",
    "Sent": 3,
    "Delivered": 0,
    "Opened": 0,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 0,
    "SoftBounced": 0,
    "Suppressed": 0,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "coatest082522",
    "Email": "Email2",
    "Sent": 3,
    "Delivered": 0,
    "Opened": 0,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 0,
    "SoftBounced": 0,
    "Suppressed": 0,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "coatest082523",
    "Email": "Email2",
    "Sent": 3,
    "Delivered": 0,
    "Opened": 0,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 0,
    "SoftBounced": 0,
    "Suppressed": 0,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "coatest082801",
    "Email": "Email1",
    "Sent": 1,
    "Delivered": 1,
    "Opened": 1,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 0,
    "SoftBounced": 0,
    "Suppressed": 0,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "coatest082810",
    "Email": "Email1",
    "Sent": 1,
    "Delivered": 1,
    "Opened": 1,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 0,
    "SoftBounced": 0,
    "Suppressed": 0,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  },
  {
    "Program": "coatest082901",
    "Email": "Email1",
    "Sent": 11,
    "Delivered": 8,
    "Opened": 4,
    "Clicked": 0,
    "FailedToProcess": 0,
    "HardBounced": 2,
    "SoftBounced": 0,
    "Suppressed": 1,
    "MarkedAsSpam": 0,
    "Unsubscribed": 0
  }
]

**Comment by paagla123** [comment]
@coa0329 who is assigned to this one?

**Comment by paagla123** [comment]
@coa0329 the only parameters you need to provide are ai=Account ID, and fd/td => From and to dates.
td should always be today's date. DO we have any publish date or equivalent saved in cDB that we can use as fd? The remaining values should be unchanged.

**Comment by coa0329** [comment]
@paagla123 

We have publishDate in cDB.

**Comment by paagla123** [comment]
@coa0329 can we use min(publishDate) as fd?

**Comment by coa0329** [comment]
![006](https://user-images.githubusercontent.com/7914690/31645648-6b7b4394-b327-11e7-9de0-28db91bd89c3.JPG)

Are we talk about this section ?

**Comment by paagla123** [comment]
@coa0329 - Yes that section, and when we click on the VIEW MORE REPORTS link next to it. Pulls up the graph.

**Comment by daver78** [comment]
@paagla123 and @coa0329 to be clear, pressing the "VIEW MORE PERFORMANCE REPORTS" pulls up more than one graph:

![image](https://user-images.githubusercontent.com/7561473/31646245-95badda8-b2b5-11e7-9ed0-65c426616f06.png)

**Comment by coa0329** [comment]
Fixed on stage.

@paagla123 @daver78 
![009](https://user-images.githubusercontent.com/7914690/31658677-e83e2480-b35b-11e7-8e33-7bb50e63689d.JPG)

Section C can show data from https://studio.dashboard.mdl.io/api/Report//GetAdminReportData

What is data to show in section A and B ?
Do you want to show the sum of each columns in them ?

**Comment by paagla123** [comment]
@coa0329 when I run https://studio.dashboard.mdl.io/api/Report//GetAdminReportData?rn=allprogram_allemail_detail&si=0&ai=679&st=0&fd=10/05/2017&td=10/17/2017&seed=false&datasourceType=redshift I get a different set of data than what you are displaying. Let's discuss today. Thanks for getting this off and running.

**Comment by daver78** [comment]
@paagla123 and @coa0329 thank you both for pushing forward on this.  I can't wait to get my hands on it and give it love when you're ready :)

@paagla123 as I mentioned this morning, please ask Ali to create *exactly* what you need if the endpoints don't exist.  Feel free to invite him to this repo if that will speed things up for you.

**Comment by coa0329** [comment]
@paagla123 
The call you run return data for every campaigns of account 679 from 10/05 - 10/17.

I must write to code to get data for the selected campaign from that call from 10/17-10/17 to show.

Section C in the image shows data from that call for this campaign.

I ask about Section A and B. 
What is data to show in section A and B ?
Do you want to show the sum of each columns in them ?
What do you want to show when user click Details in section C ?

==========

It will be easier for me if I can pass campaign name to the call and it return only data for that campaign.

**Comment by paagla123** [comment]
@coa0329 do you have access to program id?

**Comment by coa0329** [comment]
@paagla123 

https://studio.dashboard.mdl.io/api/Report//GetAdminReportData?rn=allprogram_allemail_detail&si=0&ai=679&st=0&fd=10/05/2017&td=10/17/2017&seed=false&datasourceType=redshift

No parameter for program id in the call.

**Comment by paagla123** [comment]
@coa0329 I know that. I am asking if you have access to it. If you do, I can have Ali add program ID to teh call. I will also get him to return the summary level data for sections A and B, so that you don;t have to worry about them.

@daver78 do we have the exact same data in sec A & B?

**Comment by coa0329** [comment]
@paagla123 

We have program id.

**Comment by daver78** [comment]
@paagla123 Right now, yes.  But once @coa0329 does the work, I'm going to replace the current chart in "A" and find a Funnel that can show the conversion rate from each step.

**Comment by paagla123** [comment]
I see

**Comment by daver78** [comment]
@paagla123 Did you invite Ali to the repo yet?  May be helpful.

Also: Please remember that even though I haven't included this in the UI yet, **we want Users to be able to drill-down to the row-by-row listing of the Contacts behind each # we present**.  When you have him create these endpoints, please be clear on how this will work so that we can implement this soon.

**Comment by daver78** [comment]
@paagla123 Can you put your spec here for the endpoints you're requesting?  I think we should sanity check them before Ali and others do.

**Comment by daver78** [comment]
@paagla123 and @coa0329 Why do you need to wait for anyone to start using RedShift?  Why don't you log in and initiate yourself?

![image](https://user-images.githubusercontent.com/7561473/31782515-fa496d4c-b4af-11e7-91f9-9d76ccfc2c26.png)

**Comment by paagla123** [comment]
I am going to close this one and start a new issue with teh discussions I've had with Dave and Ali separately.
