### ISSUE TITLE
Show studio error and convert to friendly version.

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#49]
_From @paweenwich on August 25, 2017 9:6_

- Try catch all API error and show to user (by trying to map it to friendly version first)
- map should implement in json for easy editing.  

_Copied from original issue: coa0329/Bhaang#13_

**Comment by paagla123** [comment]
Coa - do you have a list of errors you have received so far? If not, can we go back and create one please?

**Comment by paagla123** [comment]
_From @coa0329 on August 29, 2017 0:55_

@paagla123 
do you have a list of errors you have received so far? 
- No, I don't.

If not, can we go back and create one please?
- We can re-create some of them.

**Comment by paagla123** [comment]
_From @paweenwich on September 5, 2017 7:10_

Show ErrorCode and ErrorMessage now

**Comment by daver78** [comment]
@paagla123 Closing for now.

**Comment by paagla123** [comment]
@daver78 these are all caused by moving issues from old repo to the new one.
