### ISSUE TITLE
[PABP: Step 3] Show how many people are in your selected segment(s)

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#52]
As a marketer, I need to know how many people are in my segments (in the dropdown), and how many total people I've selected (in the event that I'm adding multiple segments).

So here, do something like LIST NAME [xx people]:
![image](https://user-images.githubusercontent.com/7561473/30746059-4a1df742-9f5d-11e7-995b-c0df121fd356.png)

... and here, put the total number of people on the right:
![image](https://user-images.githubusercontent.com/7561473/30746043-37ac7bce-9f5d-11e7-9740-be330400a1da.png)
Bear in mind for this one, you can't just add the sum of people from the first view -- You need to run the whole TA.

**Comment by daver78** [comment]
@paagla123 Assigning to you as a sanity check for the importance of the idea.  If you agree, please prioritize and assign to the right person?

**Comment by paagla123** [comment]
@daver78  agreeed.

**Comment by daver78** [comment]
@paagla123 OK.  You'll discuss & assign from here, yes? After it is done we can give it love.

**Comment by paagla123** [comment]
@daver78 what did we decide re how we will handle join of multiple audiences?

**Comment by daver78** [comment]
@paagla123 No conclusion.  I think it can be done with a TA, you think we have to get a list and unique-ify it.  Not sure which of us is right ... can you think about it?

**Comment by paagla123** [comment]
@coa0329 can we please assign someone to this and evaluate the effort?

**Comment by coa0329** [comment]
@AumpaiFung will fix this

**Comment by AumpaiFung** [comment]
@paagla123  Stage fixed. 

NOTE: 
1. If have not choose any audience, system will use default-filter (is seed). 
2. Amount of people is not real-times sync, maybe sometimes it's will not the same.

**Comment by paagla123** [comment]
Perfect
