### ISSUE TITLE
[PABP: Step 4] Little to-do headline is still hardcoded; needs to be dynamic

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#56]
The little list should be dynamic based on my sections:

![image](https://user-images.githubusercontent.com/7561473/30777283-20430d12-a06c-11e7-851d-53d0eb9d05e0.png)

**Comment by daver78** [comment]
@paagla123 Can you discuss with team then assign as required?

**Comment by paagla123** [comment]
@coa0329 Can you please assign to someone to fix the hardcoded subject line in the 4th step of the blog?

**Comment by coa0329** [comment]
@jiewsone will fix this.

**Comment by jiewsone** [comment]
Fixed on stage with issue #107

**Comment by paagla123** [comment]
Fixed in Stage

**Comment by daver78** [comment]
@paagla123 Forgive me I haven't checked -- but this portion is in both blueprints.  Did @jiewsone  fix it both places?

**Comment by coa0329** [comment]
Yes, @jiewsone fix them both.

**Comment by paagla123** [comment]
@daver78 yep
