### ISSUE TITLE
[Audiences] Review UI love applied by Coa to importContact.php

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#6]

**Comment by daver78** [comment]
@paagla123 This still needs work.  I haven't done it yet.

**Comment by paagla123** [comment]
@daver78 OK

**Comment by daver78** [comment]
![image](https://user-images.githubusercontent.com/7561473/31844820-13aade3c-b5b0-11e7-8515-706e3848db62.png)

![image](https://user-images.githubusercontent.com/7561473/31844836-2e5300ac-b5b0-11e7-9ae4-b965036e3f3b.png)

**Comment by daver78** [comment]
@paagla123 This is ready for your review.  Let me know what other changes you suggest after you play with it.

**Comment by paagla123** [comment]
@daver78 do you have a link I can play with? Based on screenshots it looks good.

**Comment by daver78** [comment]
@paagla123 It's checked into the `stage` branch, so if @coa0329 or @paweenwich can deploy for you this weekend, you can play there.

Alternatively, text me when you're ready and I'll wake up the sleeping giant (aka my dev machine).

**Comment by coa0329** [comment]
@paagla123 @daver78 

I pull the code to stage.

**Comment by daver78** [comment]
@coa0329 Thank you.

@paagla123 You should test this and review.  Make any notes here for fixes.

**Comment by paagla123** [comment]
@daver78 I have tested once - need to go through a couple more rounds

**Comment by daver78** [comment]
@coa0329 I discussed this with @paagla123, and we would like to show the first rows of the uploaded file beneath the mapping section:

![image](https://user-images.githubusercontent.com/7561473/32015601-6c4b6b0a-b976-11e7-8e42-640abfc60394.png)

Can you do that, please?

**Comment by coa0329** [comment]
@daver78 @paagla123 
Show the first 3 rows. : Fixed on stage.

**Comment by daver78** [comment]
@coa0329 Thank you.  @paagla123 You will test this?

**Comment by paagla123** [comment]
Tested. Closing.
