### ISSUE TITLE
Reference the issue # when committing

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#61]
Let's have people reference the issue # when they commit.  Makes keeping track of what's in progress easier.  `git commit -m "I did blah blah for #20"` is all that's required (specifically, the `#20` portion)

**Comment by daver78** [comment]
@paagla123 TExt

**Comment by daver78** [comment]
@paagla123 If we do the feature-branch git strategy, we can do this as long as @paweenwich knows which changes to merge.

**Comment by paagla123** [comment]
@paweenwich @daver78 @coa0329 we also need to be able to identify which fixes from staging are going to production and which ones are not. We should not be sending everything from staging to prod, as all issues in staging may not have been fixed.

**Comment by daver78** [comment]
@paagla123 I think the question re: which items move requires some research to evaluate the various options.  How important is it now?

**Comment by daver78** [comment]
@paagla123 Will you make sure people do this correctly?  As you can see from Friday's issue with the templates, it is important to do this so there is transparency and visibility for everyone.

**Comment by daver78** [comment]
@paagla123 Can you and @paweenwich confirm we're doing this now?  As you can see from some of the recent commit issues, this will help us stay on track.

**Comment by paagla123** [comment]
@coa0329 @AumpaiFung @jiewsone - can all of you please add a comment on this issue to let us know if this is being followed? I will close the issue once I get YES from everyone. Thx

**Comment by jiewsone** [comment]
Yes. #61

**Comment by coa0329** [comment]
YES

**Comment by AumpaiFung** [comment]
yes
