### ISSUE TITLE
Rename campaign name feature

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#62]
We need to be able to rename a campaign name by being able to click on the name and type over it. Style should be similar to how change subject for emails in Blog Emails

**Comment by paagla123** [comment]
@coa0329 can you please assign some one to this?

**Comment by coa0329** [comment]
@jiewsone will fix this

**Comment by jiewsone** [comment]
I try to change Campaign Name label to editable on my local but I have css problem like this
![campaign-name](https://user-images.githubusercontent.com/30495168/31168836-f6855e0e-a920-11e7-943e-054724b94a26.JPG)
![campaign-name2](https://user-images.githubusercontent.com/30495168/31168889-2ad44256-a921-11e7-80e0-c6e69c948aa3.JPG)
@daver78  Dave, Could you please change it before? Then I will insert code in your version.

**Comment by paagla123** [comment]
@jiewsone I am not sure exactly what you want. I see that you have a CSS problem. What is teh nature of the problem and what would you like from @daver78 ?

**Comment by paagla123** [comment]
@jiewsone please note that @daver78 is at a Trade Show and may not be able to work on this for a while. He suggested that it may be faster if you go through his code - it should be pretty straightforward for you to figure out. Please also review the code where we change the email subject. Thanks

**Comment by jiewsone** [comment]
Fixed on stage.

**Comment by paagla123** [comment]
Ooh - works great - thank you
