### ISSUE TITLE
Research how to only move certain features to staging, production

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#64]
This is to track @paagla123's  request for this idea. Things to look into:
	•	blue/green deployment with git
	•	right git workflow for this idea
	•	feature toggle idea with git; what is latest thinking on this by others

**Comment by paagla123** [comment]
@daver78 with the use of Feature Toggle with git - can we now close this?

**Comment by daver78** [comment]
@paagla123 Correct.  Closing.
