### ISSUE TITLE
Apply chosen to switch account pull-down

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#67]

**Comment by daver78** [comment]
@paagla123 This should be done.

**Comment by paagla123** [comment]
@daver78 in staging?

**Comment by daver78** [comment]
@paagla123 I work on the `staging` branch.  I think you're confusing that with the staging environment?

**Comment by paagla123** [comment]
@daver78 @paweenwich Yes

**Comment by daver78** [comment]
@paagla123 Closing for now.  If you find an issue, open new issue.
