### ISSUE TITLE
Make “Track Conversions” something that loads after clicking “Advanced” or something 

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#69]

**Comment by daver78** [comment]
@paagla123 Done.  Switching to you for verification.

**Comment by paagla123** [comment]
Are you merging them to staging @daver78 ?

**Comment by daver78** [comment]
@paagla123 This is why I suggested/asked that everyone add the issue # to their commits.  If you click the commit note above:

![image](https://user-images.githubusercontent.com/7561473/30942689-36a5ff50-a3a1-11e7-932a-c980caf1efe5.png)

... you'll see what was changed and on which branch:

![image](https://user-images.githubusercontent.com/7561473/30942693-3dbfd19e-a3a1-11e7-9997-8fff287d146b.png)

Our process remains the same: @paweenwich has asked that I (Dave) work on the `staging` branch.  Some of the others are doing feature-branching strategy.

When Kwang gets in, he does any necessary merges to the `staging` branch, then deploys that to the staging environment.

**Comment by paagla123** [comment]
@daver78 @paweenwich I see. So I cannot test yet.

**Comment by daver78** [comment]
@paagla123 As of 7pm last night, yes.  That's the time @paweenwich does the update.

**Comment by daver78** [comment]
@paagla123 never even noticed :( So closing for now unless there is an issue.
