### ISSUE TITLE
Odd email in my inbox.  Is it for Kushal?

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#74]
Case details: Hellow.

How is your day?

My name is Olga and you? Are  you frequently on this site?
I like your profile and want to chat with you, but unfortunately you
was online 3 days ago.
I hope that you will write to me soon. I guess that we will have many
topics to talk about.
Do you have gmail?

Email bernasilo1985@rambler.ru

Sincerely yours Olga.

**Comment by paagla123** [comment]
@daver78 I am too old for this! This is probably for the young studs like @coa0329 or @jiewsone . Closing this one!
