### ISSUE TITLE
mixed http and https in the include files.

### ISSUE THREAD

**Issue by coa0329** [coa0329/BhaangWeb#76]
Mixed http and https in the include files.

**Comment by daver78** [comment]
@paagla123 and @paweenwich Is this still open?

**Comment by paagla123** [comment]
@daver78 I believe still open

**Comment by coa0329** [comment]
Still open wait for @paweenwich to check,

**Comment by coa0329** [comment]
@AumpaiFung

We set timezone in some php to PDT.

Please change them from date_default_timezone_set('America/Los_Angeles'); to date_default_timezone_set('UTC'); too.

**Comment by AumpaiFung** [comment]
@paagla123 
Stage fixed.

**Comment by paagla123** [comment]
@AumpaiFung @coa0329 any idea how to verify? Thanks - Kushal

**Comment by paagla123** [comment]
@coa0329 need to resolve is Studio REST API calls should use https

**Comment by coa0329** [comment]
@paagla123 

https://studio.mdl.io/REST/PHPSampleAPICall.zip

The example code use http.

**Comment by paagla123** [comment]
@coa0329 @AumpaiFung  Jason says should always be https - sample is wrong.  So let's fix this.

Can you please also add him to this repo (javpowell)

**Comment by coa0329** [comment]
@paagla123 
I send the invite to @javpowell

**Comment by paagla123** [comment]
Thx. @coa0329 did you see my note on using  https for APIs?

**Comment by coa0329** [comment]
@paagla123 

Yes, I test on local. It works fine. 

I will upload to stage this evening.

**Comment by paagla123** [comment]
@paweenwich @coa0329 @daver78 I believe this is ready to be closed - right?
