### ISSUE TITLE
[PAEB] Accordion love

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#86]
![image](https://user-images.githubusercontent.com/7561473/30977864-b8e6d188-a42d-11e7-995b-10133ada2b49.png)

[DONE] **[A]** This was the hardcoded title from my mockup.  Should be based on what the User enters.

**[B]** Alignment should match what we did in eBook (using `<div>` instead of `&nbsp;`)

**[C]** Sub-heading needs to be capitalized like others

**[D]** Sub-heading should talk about Schedule not Emails

**[E]** This is hardcoded and does not change based on the User's input; it should update based on my configuration.

**Comment by daver78** [comment]
After:

![image](https://user-images.githubusercontent.com/7561473/30983687-fc64eae6-a43f-11e7-8841-0f738633f3dc.png)

**Comment by daver78** [comment]
@paagla123 This is better than before, perhaps good enough for now.  The only one I did not do is [E].  That also remains open for PABP.

**Comment by daver78** [comment]
@paagla123 Closing this for now -- except that [E] remains open for both Blueprints.

**Comment by paagla123** [comment]
@daver78 I will test and open a new issue
