### ISSUE TITLE
[PAEB] Landing Page Welcome Page Love

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#87]
![image](https://user-images.githubusercontent.com/7561473/30978398-4ac40fe8-a42f-11e7-8a90-eefd06bc9312.png)

**[A]** This `<h>` should be pre-populated with the name of the eBook entered in Step 1 // _Can't do this.  Asked @paweenwich for help.  For now, I put some better default text._

**[B]** We need to replace this with a default image (like we did with Blog Post) (and the logo image may need some HTML work so that it doesn't sit on the `<h>` // _Created a default image._

**[C]** The text needs to be updated with informative default text (like we did with Blog Post) // _Updated this text._

**[D]** When you first come in, would be good to see a silhouette (maybe red dashed lines or something) with the words "PICK A FORM USING THE DROPDOWN ABOVE" or something like that. // _Added `div class=well` for a bit of styling around the form, but this doesn't hit the mark.  Will open a spearate issue._

**[E]** These forms needs `chosen` styling // _@paweenwich and @paagla123 Can you assign someone?_

**Comment by daver78** [comment]
@paweenwich I notice that in the default content, we do this:

`"LANDINGPAGE-HERO-IMAGE": "<img src='https://s3.amazonaws.com/mindfiredavinci/img/My+Fantastic+eBook.png' class='img-responsive' border='0' style='display:block'>",
`
Did we find it necessary to embed HTML with that var as opposed to just the img location on S3? I'd rather put the styling attributes in the HTML template.  Let me know if there is a reason we did it this way.  If not, I'll change it.

**Comment by daver78** [comment]
Not great, but a bit better:

![image](https://user-images.githubusercontent.com/7561473/30988538-733616e0-a44f-11e7-91f0-041a9e17cacc.png)

**Comment by daver78** [comment]
@paagla123 I'm going to stop on this one.  You can check and if OK we'll close it.

**Comment by daver78** [comment]
@paagla123 I'm going to close it.

**Comment by paagla123** [comment]
@daver78 its ok to keep this closed. I believe there is a duplicate issue open. I will open issue with specific questions, if I have any.
