### ISSUE TITLE
[PAEB] Thank-you Page Love

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#88]
![image](https://user-images.githubusercontent.com/7561473/30978653-02213a4e-a430-11e7-9805-cf9d2a82ab78.png)

**[A]** Same issue as the previous page where log sits on top of text below it

**[B]** The name of the eBook needs to default to what the user entered in Step 1.  Right now it is hardcoded.

**[C]** Remove this for now (good feature, but we don't have it yet)

**[E]** User should be able to edit text on button

**[D]** Is this dynamic?  I don't think so, but needs to be.

**Comment by daver78** [comment]
Here's how we look now:

![image](https://user-images.githubusercontent.com/7561473/30989697-6db19aec-a453-11e7-8f17-45ca8cf15c07.png)

**Comment by daver78** [comment]
@paagla123 Done for now.  Please advise other changes we need, or close for now.

**Comment by daver78** [comment]
@paagla123 We can close this -- but see question about about website address.

**Comment by daver78** [comment]
@paagla123 Closing this -- but see above question about website address var.  Add issue if you agree, ok?

**Comment by paagla123** [comment]
@daver78 got it
