### ISSUE TITLE
[PAEB] Microsite landing page HTML should populate favicon

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#90]
![image](https://user-images.githubusercontent.com/7561473/30978856-acd6136a-a430-11e7-8456-9c97714edc1d.png)

Use the logo uploaded by the User.

**Comment by daver78** [comment]
@paagla123 I did this by using the logo uploaded by the user --  but I'm not sure it is OK.  

I forgot to consider that the icon needs to be like 16x16 or 32x32.  We should probably give the user a way to crop an image to that size based on their uploaded logo (eventually).

What do you think we should do for now?

**Comment by daver78** [comment]
@paagla123 Let me know re: above.

**Comment by paagla123** [comment]
@daver78 OK agreed
@coa0329 do you need to add a variable in the MAML to hold the a link to this image?

**Comment by coa0329** [comment]
Should we allow user to upload favicon in setting ? Then we add defCompanyFavicon to keep the link.

We can put <link rel="shortcut icon" type="image/png" href="{{defCompanyFavicon}}"/> in the template,

**Comment by coa0329** [comment]
Should we allow user to upload favicon in setting ? Then we add defCompanyFavicon to keep the link.

We can put it in the link in the template,

**Comment by paagla123** [comment]
I see a favicon now, I believe it is the logo. @daver was that the intention?

![image](https://user-images.githubusercontent.com/29718335/31146082-546e7e34-a83a-11e7-96f7-d51484bde99e.png)

**Comment by paagla123** [comment]
@daver78 are you ok with this or do we need a different image for the Favicon?
