### ISSUE TITLE
[PAEB] Send-test success message needs love

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#92]
![image](https://user-images.githubusercontent.com/7561473/30979111-7fba1768-a431-11e7-9e0e-b8893baa010d.png)

**Comment by daver78** [comment]
After:

![image](https://user-images.githubusercontent.com/7561473/30991138-af3225a4-a458-11e7-9ed1-ae5f449ada3f.png)

@paagla123 Any suggestions?  If not, and you're OK with it, please close.

**Comment by daver78** [comment]
@paagla123 I'm closing this for now.  Recall that this is an area where we have duplicity in our code.

**Comment by paagla123** [comment]
@daver78 this is good - thanks. I will wait for @paweenwich to get back before discussing duplicity. Also - have you looked at the published and failed to publish pop-ups?
