### ISSUE TITLE
[PAEB] Schedule and notifications UI needs love

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#93]
Should match what we did in Blog:

![image](https://user-images.githubusercontent.com/7561473/30979179-bb77824a-a431-11e7-8bec-21469ad8398c.png)

**Comment by paagla123** [comment]
@daver78 what is the issue here - this seems ok to me - right?

**Comment by paagla123** [comment]
@daver78 can we close it?

**Comment by daver78** [comment]
@paagla123 Go ahead and close this one.  I think we will end up modifying this to handle the email/phone #s of the people who want to be alerted, right?

If you agree, let's close this and make a new issue to handle that issue.
