### ISSUE TITLE
Audiences: The audience count in the audiences main page does not get updated when contact count changes

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#94]
We added 6 records to the audience in the screenshot below - still keeps saying 3 contacts, should be 9.
![image](https://user-images.githubusercontent.com/29718335/30988691-fab18564-a44f-11e7-99b7-f5796004eedb.png)

![image](https://user-images.githubusercontent.com/29718335/30988730-13d0a764-a450-11e7-9417-853df24415c6.png)

**Comment by AumpaiFung** [comment]
Fixed on Stage.

**Comment by paagla123** [comment]
Fixed - closing
