### ISSUE TITLE
Can LANDINGPAGE-TOP-TEXT support another var inside of it?

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#95]
@paweenwich In DB `master` document `Default_PromoteEbook`, I want this:

`LANDINGPAGE-TOP-TEXT: "{{URL-eBOOK-NAME}}"` 

I tried this, but it doesn't seem to replace the `{{URL-eBOOK-NAME}}`.  Do we not support this?  Is there a way to easily fix, or a way around it?

If you need to assign this to someone else to answer, no problem.

**Comment by daver78** [comment]
@paagla123 Can you ask @paweenwich tonight?

**Comment by coa0329** [comment]
It doesn't render in davinci.

![170](https://user-images.githubusercontent.com/7914690/31108551-4062602e-a824-11e7-969d-8222a0d27aa3.JPG)


But it will render when user visit welcome page.

![171](https://user-images.githubusercontent.com/7914690/31108567-4d751482-a824-11e7-92b5-c8ac83c27978.JPG)

**Comment by paagla123** [comment]
That is correct. @daver78 I tested this, works as stated by @coa0329 . What would you like to do here?
