### ISSUE TITLE
[PAEB] Missing div class=well around <form>

### ISSUE THREAD

**Issue by daver78** [coa0329/BhaangWeb#98]
Someone removed the div class=well around the form.  Who?  Was it for a specific reason or a mistake in the merge?

![image](https://user-images.githubusercontent.com/7561473/31020951-36bfef2a-a4e9-11e7-9889-b176420cfedd.png)

We need to fix this unless there is a technical reason we removed it.

**Comment by daver78** [comment]
@coa0329 it looks like you rolled back the updates I made in the `stage` branch to these templates.

Was it intentional?  Maybe I made some mistakes?

If not, you either didn't `git pull` when you started working or ignored the conflict message during the merge.

Can you let us know, and then fix if it was unintentional?

**Comment by coa0329** [comment]
The code we pull from git stage branch does not show the template in dropdown template in welcome and thank you page on our local environment.  

Jiew asks me to get the templates from stage server.

So I download them and they can show so I fix something then push them back to stage branch.

==========

What is the correct process to do in the future if something like this happen again ?

**Comment by daver78** [comment]
@coa0329 I left you a comment in the code.

**Comment by coa0329** [comment]
@daver78 How can I get the version your code from git ?

![154](https://user-images.githubusercontent.com/7914690/31041601-4113d3a4-a5c2-11e7-9624-9f9bcb3457a5.JPG)

**Comment by daver78** [comment]
![image](https://user-images.githubusercontent.com/7561473/31041664-176468ee-a54e-11e7-87c2-3a8e1467f3f0.png)

**Comment by daver78** [comment]
@coa0329 There are multiple ways, but from the view you were in, click on the commit ID (where I have the pink arrow).  That will show you what you checked in compared to what we had previously.  You can use what I had previously, and then debug to see if I broke the pull-down.

Let me know if I did something wrong.

@paagla123 Tagging you as FYI.

**Comment by coa0329** [comment]
How can I get all the EBOOK-LANDINGPAGE-COMPANY-THANKS.html of version 2c522d0 ?

**Comment by daver78** [comment]
![image](https://user-images.githubusercontent.com/7561473/31041698-cf1127f2-a54e-11e7-97cc-9efe6a6c100d.png)
@paagla123 FYI.

**Comment by coa0329** [comment]
@daver78 Got it. Thank you.

**Comment by daver78** [comment]
@coa0329 OK.  No prob.

**Comment by coa0329** [comment]
I push Dave's template back to stage.

**Comment by coa0329** [comment]
Fung's code has <<<< in it. It make the html code broken.

**Comment by daver78** [comment]
@coa0329 and @AumpaiFung That means that when you or @paweenwich did the merge, you ignored the conflict.  You need to resolve the conflict in the merge.  

Git uses the <<<< to mark the changes for you so you can figure out how to resolve the conflict.

**Comment by paagla123** [comment]
@coa0329 @daver78 what is the status here - do we still have the broken code?

**Comment by coa0329** [comment]
No, we don't have the broken code.

**Comment by paagla123** [comment]
@coa0329 so are we able to close this issue now?

**Comment by coa0329** [comment]
Yes we can close it.
